### ISSUE TITLE
Ionic + Angular import conflicts

### ISSUE THREAD

**Issue by Dev-it-a-dev** [beercss/beercss#104]
Import documentation is not clear enough to me.
How should I import it in angular without using cdn?

Thanks in advance

**Comment by KicKerBNU** [comment]
Hello @Dev-it-a-dev,

Assuming you are using Angular CLI just add this to your angular.json file
![image](https://user-images.githubusercontent.com/43939417/205441420-2826979f-5ff5-4573-b232-c9bc1369031e.png)

**Comment by Dev-it-a-dev** [comment]
Thanks for the fast reply. 
I've tried and followed your instructions but it won't work. 
For context, I'm using ionic environment with angular framework.

**Comment by bartduisters** [comment]
This feels like a platform specific use case - perhaps ask around in user groups for Ionic/Angular.
@KicKerBNU if it works for you, but it doesn't work for @Dev-it-a-dev, perhaps share a public repo.

Once solved, PR it in the docs where it makes sense and then this can be closed.

**Comment by Dev-it-a-dev** [comment]
> Im not familiar with Ionic but i think the Ionic classes are conflicted with Beercss. I tryed to reproduce here some Ionic environment and found a lot of CSS rules like in the image bellow:
> 
> ![image](https://user-images.githubusercontent.com/43939417/205660340-d3f5243e-9707-42a2-bb39-2cfcb4f1f166.png)

I'm changing the title of the issue to be more appropriate since it seems to be a Ionic specific problem

**Comment by leonardorafael** [comment]
I will close this, ok? We added more options to import beercss as here https://github.com/beercss/beercss

**Comment by Dev-it-a-dev** [comment]
Sure, no worries. I'm having huge workload these months so I cannot look into the problem myself for now
