### ISSUE TITLE
Support for date picker

### ISSUE THREAD

**Issue by fredsco** [beercss/beercss#109]
Is there a plan to support MD3 date picker within beercss? 

Thank you!

**Comment by devrav** [comment]
Also the native date picker does not show the calendar icon (tested on macos chrome).

**Comment by bariccattion** [comment]
Also was thinking about this... Is there any planned support? For this or other DatePicker? 
Didn't find anything in the examples

**Comment by InsightfulFuture** [comment]
> Also the native date picker does not show the calendar icon (tested on macos chrome).

On the beercss website it only works if you manually add the icon.

```
<div class="field label suffix border">
  <input type="date">
  <label class="active">Date</label>
  <i>today</i>
</div>
```

**Comment by InsightfulFuture** [comment]
I feel like this needs more attention… It is a great feature

**Comment by acroyear** [comment]
An fyi, Chrome-Mac now has a calendar as its date picker popup. Took them long enough given the spec is what, 6 years old? 😄

**Comment by LIGMATV** [comment]
Use [Datepicker.js](https://wwilsman.github.io/Datepicker.js/) should be nice too :)

**Comment by leonardorafael** [comment]
Closed, because this is inside another issue.
