### ISSUE TITLE
Standard navigation drawer

### ISSUE THREAD

**Issue by aimproxy** [beercss/beercss#110]
Is it possible to use Navigation Drawer without being a modal?

> Standard drawers can be permanently visible (best for frequently switching destinations) or opened and closed by tapping a menu icon (best for focusing more on screen content).

![image](https://user-images.githubusercontent.com/47716563/209955029-42f374bf-e4f0-413c-9cd9-f21cd9aa643b.png)

**Comment by findborg** [comment]
If you do not want to copy the css code into a new class you can do something like this to get started.
~~~
<div class="modal active" style="position: inherit;">
 <a class="row round">
    <i>inbox </i>
    <span>Inbox</span>
    <div class="max"></div>
    <div>24</div>
  </a>
  <a class="row round">
    <i>send</i>
    <span>Outbox</span>
    <div class="max"></div>
    <div>100+</div>
  </a>
</div>
~~~
