### ISSUE TITLE
Typo in index.js

### ISSUE THREAD

**Issue by mogholito** [beercss/beercss#112]
I think there is a typo in the index.js file line 3:
import "./dist/cdn/roboto-flex-cyrillic-etc.woff2";
correct filename is:
import "./dist/cdn/roboto-flex-cyrillic-ext.woff2";

**Comment by leonardorafael** [comment]
Oh, thanks for feedback, fixed in v3.0.4, updated in https://github.com/beercss/beercss/releases/tag/v3.0.0
