### ISSUE TITLE
discussions

### ISSUE THREAD

**Issue by amery** [beercss/beercss#116]
what about an official discord server so we can talk all things _beercss_, help each other, etc ? ;-)

**Comment by laurentpayot** [comment]
What about simply [enabling GitHub discussions](https://docs.github.com/en/discussions/quickstart) to keep everything in a single place?

**Comment by leonardorafael** [comment]
Nice idea @laurentpayot I'm creating now https://github.com/beercss/beercss/discussions

**Comment by amery** [comment]
Awesome!
