### ISSUE TITLE
System fonts

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#12]
Current `helpers.css` defines

```css

body {
  font-family: "Roboto", Arial, Helvetica, sans-serif;
  /* ... */
}
```

but [Material Design specs](https://material.io/design/typography/understanding-typography.html#system-fonts) say

>  For platforms outside of Android and web products, use a system typeface that is preferred on that platform. For example, iOS applications should use Apple’s San Francisco font.

Bulma does that by using the [following font family value](https://bulma.io/documentation/customize/variables/#initial-variables) (Apple, then Windows, then Roboto, then other fonts): 
`BlinkMacSystemFont, -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif`

Can we use the same font family value as Bulma (for instance) so we can conform to the Material Design specs? If so just let me know if you want me to create a PR…

**Comment by leonardorafael** [comment]
Hi, seems nice for me. We will get the default system fonts when Roboto is not present. Roboto needs to be the first because we not want to break the current behavior at moment.

Thanks!

**Comment by laurentpayot** [comment]
Cool :+1:

**Comment by coffeeandwork** [comment]
It looks like we can replace `-apple-system` and `BlinkMacSystemFont` with `system-ui`. I have created a [PR](https://github.com/beercss/beercss/pull/106) for this, hope it is ok with you guys.
