### ISSUE TITLE
typescript: provide type declarations for beercss

### ISSUE THREAD

**Issue by franok** [beercss/beercss#123]
Hi, I just wanted to give beercss a try in a vue.js typescript project.

I followed the installation instructions (`npm install beercss`) and added the import:
```
import beercss from 'beercss';
```

**Problem:** The ts-compiler issues the following error for this import:
```
Could not find a declaration file for module 'beercss'. 'my-vue-app/node_modules/beercss/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/beercss` if it exists or add a new declaration (.d.ts) file containing `declare module 'beercss';`
```

`npm i --save-dev @types/beercss` does not work, as there are no type declarations for beercss in the node_module package.

**Request:** Would it be a lot of effort for you to add declarations for the beercss module and publish a new release?

Thanks

**Comment by leonardorafael** [comment]
Are you using vite? You can bundle with it despite the compilation error. I will put this on next release. Thanks!
