### ISSUE TITLE
typo: "sufix" class should be "suffix"

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#13]
`sufix`, used in [fields](https://github.com/beercss/beercss/blob/034d4c4dc3ccdac8550f28f537a1d2579526332f/src/cdn/shared/fields.css#L209), is not an English word. [`suffix`](https://en.wikipedia.org/wiki/Suffix) is.

It would be nice to fix it (no pun intended :wink: ).

**Comment by leonardorafael** [comment]
You're right. We release a new version (1.2.3) fixing that typo.

Thanks 🍺
