### ISSUE TITLE
Floating Label Broken in Edge

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#133]
It seems that the textarea doesn't work in edge...

I checked the beercss website and the textareas did work in edge. Not sure whats up... I am using react.

I added the input and it is broken as well.

**Edge**:
![image](https://user-images.githubusercontent.com/109481728/227633709-e62e0fe2-9369-42cf-8e6a-6479bbf928b7.png)
![image](https://user-images.githubusercontent.com/109481728/227635060-429ba585-2bcb-4428-a9b3-de14e615b4eb.png)

**Chrome**:
![image](https://user-images.githubusercontent.com/109481728/227633896-b3f81dad-2571-477f-b264-e06d5f7f5659.png)
![image](https://user-images.githubusercontent.com/109481728/227634409-3c84a06a-3f89-4d8e-9c1f-eea9541c3db1.png)

**Comment by InsightfulFuture** [comment]
Resolved part of the issue. I didn't realize that the label had to be below the textarea/input for the code to work.

But, now both of the fields look like the input in chrome. I resolved the textarea by manually grabbing the clip-path from chrome.

**Comment by KicKerBNU** [comment]
Hello @InsightfulFuture, this is a print screen using Edge, everything seems to work fine here, maybe you can create a codepen showing the error ?

![image](https://user-images.githubusercontent.com/43939417/227742227-9a3f28da-d55f-46cf-9ab6-c519b997c40e.png)

**Comment by InsightfulFuture** [comment]
The beercss website seems to work fine. I think tailwind might be messing something up. I don't actually have a codepen account at the moment, but I have moved past this issue. I added the className (I am using React / tailwind) `[clip-path:polygon(0%_0%,_1.25rem_0%,_1.25rem_0.5rem,_8.8125rem_0.5rem,_8.8125rem_0%,_100%_0%,_100%_100%,_0%_100%)] empty:[clip-path:none] focus:[clippath:polygon(0%_0%,_1.25rem_0%,_1.25rem_0.5rem,_8.8125rem_0.5rem,_8.8125rem_0%,_100%_0%,_100%_100%,_0%_100%)]`. This seemed to fix it for me. 

By inspecting the beercss website I believe it is still using the JS solution for the floating labels instead of the css solution. The textarea on the beercss website has two event listeners - `blur` and `focus`. I don't have either of these in my enviroment. I have also noticed that they are still doing things with the `ui()` function.

I am going to close this issue because I have resolved it.
