### ISSUE TITLE
Use Material Rounded Symbols

### ISSUE THREAD

**Issue by guidouil** [beercss/beercss#135]
Hey all,
How can I make Beer CSS use the Rounded icons instead of Outlined ?
https://fonts.google.com/icons?icon.style=Rounded
Thanks

**Comment by leonardorafael** [comment]
Hi @guidouil 

By default we adopted the "Material Symbols Outlined" font icon.
We don't have any options for now.
Except if you replace the new font in `node_modules/beercss/dist/cdn/material-symbols-outlined.woff2`.
This issue can be a nice feature to next release!

Thanks 🍺

**Comment by guidouil** [comment]
Hi @leonardorafael 
I only found a [3Mb version](https://github.com/google/material-design-icons/tree/master/variablefont) of the Rounded symbols
So I downloaded the regular ttf and converted it to woff2 online.
It looks like it's working but I can't make it load into my project after building, a problem with the fonts loading with this message in the console : "OTS parsing error: invalid sfntVersion: 1008813135"

You can see my "working branch" here : https://github.com/guidouil/beercss/tree/rounded

Can you help me make it work ?

**Comment by leonardorafael** [comment]
We created a `--font-icon` variable so you can change the name of it. 
Done in https://github.com/beercss/beercss/releases/tag/v3.1.2
