### ISSUE TITLE
Select option with value of "" set as disabled and selected displays active on top.

### ISSUE THREAD

**Issue by cryptanym** [beercss/beercss#137]
Using select with an option that is default selected with a value of "" allows the required attribute to work correctly, and forces the user to make a selection rather than just accepting the first one as what would happen without a disabled default value.

Although even when adding the active class to the label if the value is "" it gets removed and overlays the text.

Here is a codepen of the problem:
https://codepen.io/1971562171/pen/xxyOXVW

**Comment by leonardorafael** [comment]
Fixed in https://github.com/beercss/beercss/releases/tag/v3.1.2
