### ISSUE TITLE
selects: clicking on the dropdown icon does not display the options

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#14]
For [selects](https://www.beercss.com/#selects), clicking on the dropdown icon (or any icon) does not display the options.

It is quite confusing because I (and other people too I think) click on the dropdown icon first to display the options. I was thinking the whole select was not working.

Do you think it is possible to fix it in pure CSS?

**Comment by leonardorafael** [comment]
Hello again,

Nice question @laurentpayot ! Yeah it's possible. You can use `back` or `front` helpers in your element.
See a codepen here https://codepen.io/leo-bnu/pen/dyRNeJP

This helps you?

**Comment by laurentpayot** [comment]
Awesome. Thanks @leonardorafael for your responsiveness :+1: 

Is it documented somewhere? Anyway don’t you think it is worth adding the `back` class to the [select examples](https://www.beercss.com/#selects) of beercss.com?
