### ISSUE TITLE
Number input label overlap

### ISSUE THREAD

**Issue by cryptanym** [beercss/beercss#140]
The HTML number input spec allows the user to enter things such as (e . - +), if you enter these invalidly in a number input field and unfocus from it the label will overlap the text.

Here is a quick codepen for testing.
https://codepen.io/1971562171/pen/QWZGLZN

Another example is if "9.0122222900391E-5" is entered it works fine, but removing the last 5 and unfocusing from the field will cause it to become invalid and the issue happens.

**Comment by leonardorafael** [comment]
Hi, 

This is a bug from `<input type="number">`. I can't get the invalid number from input. The input always returns `input.value === ''` and `input.valueAsNumber === NaN`. The rule is "if the input value is empty the label returns to origin". We will try find a solution for this.
