### ISSUE TITLE
Round buttons by default?

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#142]
The [MD3 button guidelines](https://m3.material.io/components/buttons/guidelines#1edebefa-7d0f-42cf-beda-15fb71996c0e) say:
> **Button containers have fully rounded corners**
![image](https://user-images.githubusercontent.com/2776142/233373403-bdc691d1-f885-4306-9116-a3f05135f9f8.png)

Shouldn’t we have `round` buttons by default, and use a `square` class for other buttons?

**Comment by cryptanym** [comment]
I agree with this, I have the round class on all my elements, it should be the default.

**Comment by laurentpayot** [comment]
> I have the round class on all my elements

Same for me...

**Comment by KicKerBNU** [comment]
np for me putting the round buttons as default, especially if it has documented in MD3 guideline

**Comment by leonardorafael** [comment]
I'm working on next release with this https://github.com/beercss/beercss/tree/v320
