### ISSUE TITLE
ui is not defined

### ISSUE THREAD

**Issue by strat-ileris** [beercss/beercss#143]
I need  `ui('#modal')` in a function but react pops an error   `Line 34:21:  'ui' is not defined  no-undef`  what else should i import apart from "beercss"

**Comment by KicKerBNU** [comment]
Hello @strat-ileris  maybe you can give us more information about your project stack and how to reproduce it ? With more information it can be easier to help you.

**Comment by InsightfulFuture** [comment]
Did you fix this? I have the same issue.

**Comment by KicKerBNU** [comment]
@InsightfulFuture Maybe you can create an codepen example ? With your example we can understand better your case.

**Comment by InsightfulFuture** [comment]
Thanks! I am more interested in using `ui(“theme”, from)` to update the theme based on user preference.

**Comment by InsightfulFuture** [comment]
Is there a way to change the theme via `data-ui`? Or a way to directly import ui (something like `import { ui } from 'beercss'`)?

**Comment by InsightfulFuture** [comment]
It's been a while and I haven't heard back. Any updates on this?

**Comment by KicKerBNU** [comment]
Sorry @InsightfulFuture im just switched my working company and was very busy. In the weekend i will try to make an React change theme example.

**Comment by InsightfulFuture** [comment]
Thanks a lot! This will be very useful to me and others with react!

**Comment by KicKerBNU** [comment]
Hello @InsightfulFuture 

If you want to change themes the documentation recommend to you use Dynamic Colors.
![image](https://github.com/beercss/beercss/assets/43939417/fcfde54c-1977-4c8e-8827-a6c49d2463d0)

Here you can have access to the repository:
[Material Dynamic Colors Repository](https://github.com/leonardorafael/material-dynamic-colors)

Here i created an extremely simple test repository
[Dynamic Colors usage example](https://github.com/KicKerBNU/dynamic-colors)

Hope it helps you 🍺
