### ISSUE TITLE
Outlined <input> with non-empty value and label causes label / outline render clash

### ISSUE THREAD

**Issue by kimballa** [beercss/beercss#144]
Hello,

I am using the themed `<input/>` element in a React component where I also bind its `value` attribute to a React state variable like so:
```js
function MyInput(props) {
  [myVal, setMyVal] = useState("something not empty");
  return (
    <div className="field border label">
      <input value={myVal} onInput={e => setMyVal(e.target.value)} />
      <label>{props.label}</label>
      <span className="helper">{props.helper}</span>
    </div>
  );
}
```

The non-empty nature of `myVal` makes the label "float up" out of the text field and into the border automatically, but the border renders through it, like in this screenshot:
![image](https://user-images.githubusercontent.com/87376/235295707-d9edf410-c13a-4f8c-a6ba-6e7eea706a70.png)

After clicking on the `<input>` to give it focus, the border / label overlap resolves itself, and it remains resolved for the remaining lifetime of the page. But before that user interaction, the `<input>`'s label has the unintended "strike-through" effect.

**Comment by KicKerBNU** [comment]
Hello @kimballa 

I have two suggestions,

First - Make sure you imported the beer.min.js:
`<script type="module" src="https://cdn.jsdelivr.net/npm/beercss@latest/dist/cdn/beer.min.js"></script>`

Second - You can use the ui() function to make sure the input is updated. (Needed only in special cases).

**Comment by InsightfulFuture** [comment]
I would also suggest replacing
`<script type="module" src="https://cdn.jsdelivr.net/npm/beercss@latest/dist/cdn/beer.min.js"></script> `
With
`<script type="module">import ‘https://cdn.jsdelivr.net/npm/beercss@latest/dist/cdn/beer.min.js’</script> `

**Comment by kimballa** [comment]
beercss is definitely imported. I installed it with `npm` and used the manual-from-dist import method to develop, because NextJS does not allow you to directly import global css in the `App` component:

```js
import "beercss/dist/cdn/beer.min.css";
import "beercss/dist/cdn/material-symbols-outlined.woff2";
import "beercss/dist/cdn/material-symbols-rounded.woff2";
import "beercss/dist/cdn/material-symbols-sharp.woff2";
import "beercss/dist/cdn/roboto-flex-cyrillic-ext.woff2";
import "beercss/dist/cdn/roboto-flex-cyrillic.woff2";
import "beercss/dist/cdn/roboto-flex-greek.woff2";
import "beercss/dist/cdn/roboto-flex-latin-ext.woff2";
import "beercss/dist/cdn/roboto-flex-latin.woff2";
import "beercss/dist/cdn/roboto-flex-vietnamese.woff2";

import beercss from "beercss/dist/cdn/beer.min.js";
import materialDynamicColors from "material-dynamic-colors/dist/cdn/material-dynamic-colors.min.js";
```

BeerCSS is definitely theming the UI components so it is working.

@KicKerBNU are you saying that the expected behavior is that if React injects a default value into a form field, I need to explicitly call `ui("#input-id")` to ensure it renders properly? I would have expected that the `<input>` would have some sort of event listener already bound to it which ensures it renders correctly when its `value` attribute changes.

**Comment by kimballa** [comment]
Actually, I realized I need to qualify this bug report further. My app has two `<div class="page">...</div>` pages controlled by `<a>` elements within an associated `<div class="tabs">...</div>`. There are `<input>` elements within each page div.

One of these page divs also has the `active` class present from the start. (i.e., `<div class="page active">...</div>`)

When the default values are injected into the inputs, the "active" page correctly redraws the label without the strikethrough... after a delay. (The unintentional strikethrough is visible for a frame; in the first render pass, the default form input value is present in the main text area of the `<input>` and the label is shrunk into the border, but the border is drawn as an unbroken ring. Then in a second pass (after a brief but visible delay) it clips the border path so it doesn't strike through the label. That _also_ seems like a minor bug to me since that intermediate state doesn't seem intended for user viewing.)

On the inactive page, however, that second (`onLoad`-based?) render pass doesn't happen. When I use the nav tabs to activate the second page, I get the form as-shown in my screenshot above with the in-border label but no border line clipping applied until I directly focus each individual `<input>` element.

I don't think it's reasonable for a consumer of the `<div class="page">` and `<input>` beercss components to need to specifically invoke javascript-based redraw functions to properly initialize `<input>` elements within a `page`--but only if the page is not `active`. Sometimes it would not be possible to know whether a given `<input>`  is being injected within a `page`, or whether or not that page is active.

**Comment by InsightfulFuture** [comment]
One thing that I would try is inspect to find the `clip-path` style on the input and manually add it if the input value isn't blank. For example with the input, 
```
<div class="field label border" className="active">
  <input />
  <label>VMax</label>
</div>
```
The actual input element has the style
```
style="clip-path: polygon(0% 0%, 1.25rem 0%, 1.25rem 0.5rem, 3.625rem 0.5rem, 3.625rem 0%, 100% 0%, 100% 100%, 0% 100%);"
```
When rendered in a browser.

So, if you did something like
```
<input style={myVal && { clip-path: 'polygon(0% 0%, 1.25rem 0%, 1.25rem 0.5rem, 3.625rem 0.5rem, 3.625rem 0%, 100% 0%, 100% 100%, 0% 100%)' } />
```
that should resolve your issue. This is a lot more manual than it should be, but it should work.

**Comment by kimballa** [comment]
Thanks @InsightfulFuture . The clip path is a function of the length of the label text, so that's going to be a bit clumsy but I'll see if I can make it work more generically.

**Comment by KicKerBNU** [comment]
@kimballa maybe you can reproduce this bug in a codepen example ?  I have simple start here [https://codepen.io/kickerbnu/pen/ExdvJxZ](https://codepen.io/kickerbnu/pen/ExdvJxZ)

About your previous question that is not the normal behavior the input should update automatically, that's for rare cases only. 

As you can see on this simple example, if we start it with a value or if we update the input is always updated correclty,

My goal here is to help you and reproduce this bug as simple as possible 🍺

**Comment by kimballa** [comment]
OK, I pulled the relevant code out into a pen here: https://codepen.io/kimballa/pen/XWxeger

Click on "right tab" and observe the 'strikethrough' on the label associated with the input in that tab.

This could _probably_ be reduced in size a bit (sorry 'bout that) but I included the React components I made to wrap the relevant beercss styling/elements to keep it close to how I wrote it in my own codebase.

Hope this helps.

**Comment by kimballa** [comment]
Also, this codepen is naturally running React entirely client-side. That is still sufficient to see the issue in the right tab.

In my app, I am using the Next-JS framework which does server-side rendering. There, the same issue (label is shrunk to the upper-left corner, but border is continuous through it) manifests on the left tab for a short but noticeable (100ms?) fraction of a second just after the page finishes loading, at which point the system seems to realize that the `<input>` has a value and the border strikethrough issue on the left tab corrects itself without needing for the user to focus the `<input>`. 

I don't know how to demonstrate that in a codepen though, since I don't think it'll run my own arbitrary-code node-js backend for me.

That's less problematic than the continuous problem on the right tab, but still detracts from an otherwise clean CSS job.

**Comment by KicKerBNU** [comment]
Hello @kimballa thanks for your time on the bug example, for some unknow reason the updated input dont know it have been updated, one simple recomendation is the use of ui() when you change the tab, for that i make an onClick event to trigger ui(). 

[https://codepen.io/kickerbnu/pen/YzJrrpo?editors=1111](https://codepen.io/kickerbnu/pen/YzJrrpo?editors=1111)

Hope it helps you
🍺

**Comment by kimballa** [comment]
Got it, that seems like a straightforward enough workaround. Thanks for the
fast response.

Cheers!
