### ISSUE TITLE
Beercss website responsive 

### ISSUE THREAD

**Issue by KicKerBNU** [beercss/beercss#145]
Refactor the html to get a better responsive view on mobile iOS

Web:
![image](https://user-images.githubusercontent.com/43939417/236621516-09231564-aa7e-42da-804d-e842931be1d8.png)
iOS:
![image](https://user-images.githubusercontent.com/43939417/236621580-bbeefc96-3321-4bc4-bbf4-221f336b2f67.png)

**Comment by KicKerBNU** [comment]
Also need some better presentation on Badges:
![image](https://user-images.githubusercontent.com/43939417/236621833-dba662d0-4f11-4120-b0d4-22cb1f4156bb.png)

**Comment by leonardorafael** [comment]
I'm working on it in the next release https://github.com/beercss/beercss/tree/v320
