### ISSUE TITLE
svelte with beercss

### ISSUE THREAD

**Issue by carlyg7** [beercss/beercss#147]
Como puedo integrar beercss en sevelte, por NPM, me da fallo en carpeta .css

**Comment by KicKerBNU** [comment]
Hello @carlyg7 

The  easiest way i found is here:
https://github.com/KicKerBNU/svelte-app

1 - `npm install beercss`
2 - Add to your app.html beercss minified css and js files, like in the image below:
![image](https://github.com/beercss/beercss/assets/43939417/ae8c837b-ba2a-4c48-8bdb-35e855b215e7)
