### ISSUE TITLE
Beercss selects

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#151]
I just checked the website after v3.20 released (Yay!), but now the round selects are broken on the site.

**Not rounded:**
![selects](https://github.com/beercss/beercss/assets/109481728/4c27c681-3d74-4384-9daa-959d6acfd643)

**Rounded:**
![rounded-selects](https://github.com/beercss/beercss/assets/109481728/362f6aaa-4ea7-4d45-8de2-8fa453e31bad)

It seems that being rounded only pushes the stuff inside the selects over a bit. When the size is `small`, `large`, or `extra`, the rounded styles work fine.

**Comment by leonardorafael** [comment]
Thanks for the catch. Fixed in [v3.2.1](https://github.com/beercss/beercss/releases/tag/v3.2.1).
