### ISSUE TITLE
Dialog regression when in nav

### ISSUE THREAD

**Issue by cryptanym** [beercss/beercss#152]
Updating my site to 3.2.2, i noticed my dropdown modals now called dialogs, I updated all my stuff to match the new standard but these modals/dialogs were inside the nav so they could drop down from below the nav, rather than overlay on top of it, this worked fine before 3.2.2. Now (h.removeClass is not a function) is printed to console when i click them.

Here is a codepen:
https://codepen.io/1971562171/pen/abRRzEV

Moving the modal outside the nav element fixes the console error, but it overlays the nav bar.

**Comment by leonardorafael** [comment]
Fixed in v3.2.3 https://github.com/beercss/beercss/releases/tag/v3.2.0
