### ISSUE TITLE
Make Material Symbols Optional

### ISSUE THREAD

**Issue by crypnull** [beercss/beercss#153]
Seeing the removal of Roboto for system fonts instead, with the option to add it back if desired, I think material symbols should also be removed from default and also be encouraged to add it back if desired, I don't use Material Symbols on my site at all I use FontAwesome with BeerCSS so without compiling my own version it's sent to the client and never used.

**Comment by leonardorafael** [comment]
Hi, Material Symbols intents to be the way to go with Material Design 3. Optionated this will hurts the DX of project. If you don't want to load Material Symbols font just add this css:

```css
:root {
  --font-icon: none;
}
```

I'm curious here. How do you use FontAwesome with Beer CSS? How do you handle checkboxes, radios, switches, etc?

**Comment by leonardorafael** [comment]
Added support for Font Awesome and Pictogrammers icons in v3.2.8 https://github.com/beercss/beercss/releases/tag/v3.2.8
