### ISSUE TITLE
Extending FAB on mobile

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#156]
On a touch device, you can't see the text inside of a `FAB` with the class `extend` until you click it. Maybe it should be expanded by default on a touch device. I believe `@media (pointer:coarse)` is supposed to apply the styles only on a coarse (touch or a non-mouse device like a TV remote) pointer. With this, if a device has both a mouse and a touchscreen, `pointer: coarse` will not match, because the primary input mechanism (the mouse) is not coarse.

**Comment by leonardorafael** [comment]
Hi, actually you can use `active` helper to expand/minimize the extended button (as you wish).

Look at this codepen example:
https://codepen.io/leo-bnu/pen/poxXWBY

**Comment by InsightfulFuture** [comment]
Thanks! I am currently using `active` on all of my extending FABS, but it would be nice to have something like `.responsive` or `.dynamic` on it to make it dynamically open/close

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.
