### ISSUE TITLE
<datalist> Support

### ISSUE THREAD

**Issue by crypnull** [beercss/beercss#159]
The <datalist> element is quite useful for many use cases, one for example is a country list that allows the user to search for their country, instead of having to scroll through all the countries, it can also be used for auto complete results.

BeerCSS currently has no styling for the datalist element but I think it would be a valuable addition to the framework.

Here is more about the <datalist> element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by crypnull** [comment]
Looking into this myself it seems styling datalist is either non existent or too hacky... I'm going to close this as it seems to be too bloated to really consider, maybe some other autocomplete library could be used.

**Comment by nitodico** [comment]
Is not possible to apply style to datalist, you should use maybe an autocomplete framework to do such work
https://stackoverflow.com/questions/10062414/is-it-possible-to-style-the-drop-down-suggestions-when-using-html5-datalist
