### ISSUE TITLE
css only floating label

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#163]
At present we are using javascript to deal with floating labels as we can see in this code block: [https://github.com/beercss/beercss/blob/acd6fe4e5aefd7c24fe4df30aa12e34f9ca92f90/src/cdn/beer.ts#L116](https://github.com/beercss/beercss/blob/acd6fe4e5aefd7c24fe4df30aa12e34f9ca92f90/src/cdn/beer.ts#L116).

It looks like it is possible to implement floating labels on input fields without javascript. There are many examples online such as this one: https://css-tricks.com/float-labels-css/. 

Having css-only floating labels may reduce the burden on the main thread. More info for the unfamiliar: https://developer.mozilla.org/en-US/docs/Web/Performance/CSS_JavaScript_animation_performance.

**Comment by laurentpayot** [comment]
Hi @coffeeandwork. I had the same issue in #15. We found a pure CSS way to activate input fields. Just add a non-empty placeholder (a space) like below:
```html
<div class="field label border">
  <input type="text" placeholder=" ">
  <label>Label</label>
</div>
```
The [CSS rules about `placeholder-shown`](https://github.com/search?q=repo%3Abeercss%2Fbeercss%20%3Aplaceholder-shown&type=code) will activate the floating label when the placeholder is replaced by an input.

**Comment by laurentpayot** [comment]
@leonardorafael this pure CSS way is not documented in the input documentation. Let me know if you want me to make a PR to add it in the docs.

**Comment by coffeeandwork** [comment]
@laurentpayot thank you for your reply. To be sure, I am not reporting a bug. I am suggesting a potential improvement to the floating label implementation as follows:

Based on the current implementation of floating labels in Beer CSS, they do not work in absence of the javascript code. I have created this demo: https://codepen.io/coffeeandwork/pen/rNQLaeY, where I have a very basic text field that has a border and a label (identical to the code you provided above). I am including the css code but omitting the js code in `<head>` . You may notice that when you click inside the text field, the label does indeed float, but the border does not move aside, it interferes with the label.

In this demo: https://codepen.io/coffeeandwork/pen/JjeKoJe, I add the javascript code, and this time, the label floats to the top of the field and the border moves aside to accommodate the floated label.

Based on my reading of the code, it's the `updateInput()` inside the `beer.ts` file that does the necessary magic. We should not need any js based magic to make the floating labels work nicely. CSS and HTML should be sufficient on their own. Here is an example where bordered text field with a floating label is implemented with javascript: https://codepen.io/devesh8/pen/MWYEJEP.

Here are some of the benefits of removing the floating label magic out of js and keeping it in css:
- Parsing and executing javascript is computationally more expensive than css, generally.
- The javascript code pertaining to the floating label implementation runs in the main/UI thread of the browser. There is wisdom in keeping the main/UI thread as free as possible. CSS based animations can happen off of the main thread.
- There is something nice about pushing out all the aesthetic concerns into CSS and reserving js for business / app logic.
- Leanness is the forte of Beer CSS. I would humbly suggest/request that it stays that way.

**Comment by laurentpayot** [comment]
@coffeeandwork Oh I see. To fix the border issue without JS I added a `background` class to the label and a bit of custom CSS to set `padding-inline`:
https://codepen.io/laurentpayot/pen/vYQKOyX

**Comment by KicKerBNU** [comment]
@coffeeandwork with this css only approach it works with two way data bindings and virtual dom changes of the js frameworks ? works on every case scenario ?

**Comment by leonardorafael** [comment]
@laurentpayot could you make a PR to include the "pure css label approach" on docs? Maybe include that padding/margin extra too (on elements that have `place-holder`)?

**Comment by coffeeandwork** [comment]
> 

I think we just need to make sure that the css only implementation works as expected when we make changes to the dom using browser's js dom api.

After that, I think we can safely assume (with a bit of testing) that it will work with vdom and data binding, because afaik, vdom and data binding have to use the js dom api to make changes to the web page, there is no other viable mechanism available today.

**Comment by coffeeandwork** [comment]
> Hi @laurentpayot, could you make a PR to include the "pure css label approach" on docs? Maybe include that padding/margin extra too (on elements that have `placeholder`)?
> 
> Of course, if you have some time for that 😁

Thanks @leonardorafael and @laurentpayot.

**Comment by leonardorafael** [comment]
> > Hi @laurentpayot, could you make a PR to include the "pure css label approach" on docs? Maybe include that padding/margin extra too (on elements that have `placeholder`)?
> > Of course, if you have some time for that grin
> 
> Hi @leonardorafael, I will try to take some time this week to update the docs, but to do this I have two questions:
> 
> 1. Do you think [Pure CSS floating label without custom CSS #168](https://github.com/beercss/beercss/pull/168) could be integrated to simplify the use of pure CSS labels?
> 2. What is ["Method 2" in the docs](https://github.com/beercss/beercss/blob/main/docs/INPUT.md#triggers)? 🤔

Oh there are no method 2, sorry 😵

**Comment by laurentpayot** [comment]
> Oh there are no method 2, sorry

No worries, I updated the docs in https://github.com/beercss/beercss/pull/173.

**Comment by coffeeandwork** [comment]
Sorry guys, one more iteration of this issue... this time for `<select>` and `<textarea>`. Here is a demo: https://codepen.io/coffeeandwork/pen/vYQgaGL

**Comment by laurentpayot** [comment]
@coffeeandwork  I fixed it in https://codepen.io/laurentpayot/pen/VwVPVra
It required the same `placeholder` and background color as explained in https://github.com/beercss/beercss/issues/163#issuecomment-1596867646.
I had to paste the dev version of the CSS because https://github.com/beercss/beercss/pull/168 has not been merged to the main branch yet.
