### ISSUE TITLE
Event Delegation

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#164]
We are a lot of event listeners to pages via the `on()` function: https://github.com/beercss/beercss/blob/acd6fe4e5aefd7c24fe4df30aa12e34f9ca92f90/src/cdn/beer.ts#L60

This works well for small pages. However, for larger pages, we could reduce memory usage by employing Event Delegation. Here is a good introduction to Event Delegation: https://www.w3docs.com/learn-javascript/javascript-events.html

**Comment by leonardorafael** [comment]
Hi @coffeeandwork ,

This could be a nice add. We will try to do that. All performance trick are welcome. 

About large pages. IMO, even on enterprise systems, large pages are a bad way to do the things. If you have a large page, you are doing it wrong.

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.
