### ISSUE TITLE
Button remains hovered when closing a dialog

### ISSUE THREAD

**Issue by jasylingling** [beercss/beercss#165]
Button remains hovered when closing a dialog, see the example below: 

![Beer_CSS_-_Build_material_design_in_record_time__without_stress_for_devs_-_Google_Chrome_2023-06-18_19-35-31_AdobeExpress (1)](https://github.com/beercss/beercss/assets/59211737/5f7a0301-91d4-4036-b634-b0aed7d38ff6)

**Comment by Tilogorn** [comment]
Any dirty workaround for this (until it's fixed)? Some JS reset() functionality? 
The same happens when a button triggers a toast, when the button is simply clicked (like in https://www.beercss.com/#buttons), ...

Thank you in advance!

**Comment by KicKerBNU** [comment]
Hello @Tilogorn you can use a blur event from javascript

Simple example here:
[codepen example](https://codepen.io/kickerbnu/pen/ExOgMXV)

**Comment by Tilogorn** [comment]
@KicKerBNU Great, thank you! Your example works perfectly. I love this community!

**Comment by leonardorafael** [comment]
Fixed the data-ui behavior to not focus on element after close a dialog.

**Comment by Tilogorn** [comment]
Fix confirmed. Thank you for your fast reaction!
