### ISSUE TITLE
Triple dash prefixed CSS variables

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#169]
I noticed there are some triple dash prefixed CSS variables [a bit everywhere in the code](https://github.com/search?q=repo%3Abeercss%2Fbeercss+---+path%3Asrc&type=code).

Is it a typo or a feature/convention? If that’s a typo, we could remove the unnecessary dash for coherence and to save some space.

**Comment by leonardorafael** [comment]
Hi @laurentpayot ,

We used `---` to identify local css variables and `--` to identify global css variables. 
We used local variables to reduce css bundle size.

**Comment by laurentpayot** [comment]
Good idea :+1:  But these supposedly local variables end up in the final "minified" build (51 triple dashes found), is that normal ? If normal, it it worth the added size ?

**Comment by laurentpayot** [comment]
I deleted my previous answer. After a look at the code I see this is a necessary evil. Too bad the CSS minifier cannot shorten them.

Thanks for your answer!
