### ISSUE TITLE
responsive class not working in Firefox

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#17]
If you open https://codepen.io/laurentpayot/pen/OJgGmEw in Firefox you'll see that 
```css
.responsive {
  width: -moz-available;
}
```
is needed to make the button responsive (take all the width).
More info on https://caniuse.com/mdn-css_properties_width_stretch .

Probably something to add in [helpers](https://github.com/beercss/beercss/blob/0fc9c5c8ed82bf8db732dfaa0c2a763bc3ccfdf6/src/cdn/shared/helpers.css#L327)…

**Comment by leonardorafael** [comment]
Added in release v1.2.5
