### ISSUE TITLE
Large font seems to add extra blank space to the right of the floating label

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#175]
If I specify a font size for my page like this:

```html
<style>
  :root {
    --size: 50px;
  }
</style>
```

Floating labels seem to leave quite a bit of blank space to the right of the label. Large the font I specify, larger the blank space gets.

Here is a demo: https://codepen.io/coffeeandwork/pen/abQmWje

![Screenshot 2023-06-21 at 12 30 18 PM](https://github.com/beercss/beercss/assets/6377739/fc3e1ea2-f8c9-4fdf-af91-7d70fe419c5f)

If you remove that `<style>` element from the `<head>` of the page, this problem goes away.

**Comment by laurentpayot** [comment]
The pure CSS method is working: https://codepen.io/laurentpayot/pen/XWyjYPG
It must be something in JS like `textWidth()`.

**Comment by leonardorafael** [comment]
I fixed it in this commit https://github.com/beercss/beercss/commit/f658671026451ba201a2f78c3895cdb138f27028. The text width (in px) wasn't dividing by the modified --size.
