### ISSUE TITLE
Some stuff here feels off

### ISSUE THREAD

**Issue by KTibow** [beercss/beercss#189]
1. Why is Material Design not mentioned in the name at all?
2. Why is Roboto or similar not used?
3. Why do some pressed states stay after clicked?
4. Why do badges have sharp corners?
5. The types of buttons are outlined, tonal, filled, etc, not primary, secondary, and tertiary.
6. Why are a bunch of roundings for FABs shown yet none of them are up to spec?
7. Why does the nav rail stick states once clicked?
8. Why is the ripple effect on the nav rail on hover instead of click?
9. Why do the chips barely resemble Material Design at all?
10. Why is the ripple always from the center?
11. Why is the vertical alignment off in the "directions" section?
12. Why do loaders glitch around upon finishing?
13. Why do dialogs fly in instead of using enter-exit?
14. Why do menus scale in instead of using enter-exit?
15. Why do the progress bars barely resemble Material Design at all?
16. Why do the buttons in "responsive" do nothing?
17. Why are the switch shapes off?
18. Why does the switch have no pressed state?
19. Why does hover stuff scale in?
20. Why is it called a toast instead of a snackbar?
21. Why does the site not follow system dark mode?

**Comment by InsightfulFuture** [comment]
For number 2, Roboto used to be used but isn't anymore. Refer to #86 for info on this.

**Comment by KTibow** [comment]
Then self-host it, or at least use system-ui instead of Arial.

**Comment by laurentpayot** [comment]
@KTibow the reason why Roboto is not used anymore was discussed in https://github.com/beercss/beercss/discussions/132.

You can replace the default font stack with whatever  you want with
```css
:root {
  --font: mybloatedrobotofont
}
```

**Comment by laurentpayot** [comment]
For point number 20, there is already an issue: https://github.com/beercss/beercss/issues/182

Did you check existing issues before dumping your list?

**Comment by laurentpayot** [comment]
For all other points I suggest removing the leading "Why" because the answer is obviously that Beercss is a work in progress of a few benevolent people trying their best to get close to the Material Design specs using limited web APIs instead of native Android APIs.

Thanks for pointing the issues, feel free to open a bug for each of them if they really matter to you.

**Comment by leonardorafael** [comment]
Hi, I would to suggest to read the project docs first and open an issue for each. And please, put some evidences/details of what is wrong at all, this can help a lot.

Of course we are trying to be 100% equal from the specs (and even more customizable using our helpers). Some minor differences can be exists, but seems not affect the UX/DX at all in most cases.

@KTibow, I will close this issue and will follow the @laurentpayot comment, ok? Select the most important questions and open an issue for each, with some evidences/details of what is wrong at all.

Thanks for the feedback!

**Comment by KTibow** [comment]
right idk
this issue was a bit of a rant ([a redundant one](https://github.com/mui/material-ui/issues/29345#issuecomment-1011833591)) - and a bit biased since i'm developing my own implementation of material 3 that matches the specs. i know that this was developed early on in M3 development, updating everything to be up to spec would be hard, and that it's still a cool library regardless.
however some stuff doesn't follow expected patterns, like how clicking the X on a chip is the same as clicking the chip, or how the site doesn't respect user dark mode. of course, i encourage you guys to fix these kinds of things, but because i'm not using this library i don't have any motivation to work with you on them.

**Comment by acroyear** [comment]
re: following system dark mode, i would prefer that be up to the application designer to decide to use it or not. it isn't like it is hard to add an event to adjust the theme. What, 4 lines of code?

I'm making a music player, for example, and those rarely are in 'light' mode no matter the system setting. Just a 'coolness' factor.

**Comment by KTibow** [comment]
m3 is designed so that everything is based on tokens. if the tokens change, including switching to dark mode, ideally your application should accommodate that just fine (just like almost all web and desktop music players).

**Comment by acroyear** [comment]
and the spec acknowledges there are reasons not to be so absolutist, as all specifications tend to be. every music player there is out there is 'dark mode'. ALL of them. most other media players (youtube is actually the rare exception *on desktop*) are also as well. On mobile, youtube is dark first.

**Comment by acroyear** [comment]
so i'll say again: why are you arguing over adding 4 lines of code yourself to achieve the same result? 4. lines. of. code.

it isn't worth the argument you're making. add the four lines, be in compliance with your interpretation of the spec, and stop complaining.

**Comment by KTibow** [comment]
my opinion is irrelevant here since i don't use the library and have no idea how dark mode is implemented.

however, i believe that when i start a new project it shouldn't default to light mode without any toggle or switching (i believe the beer css website was light mode by default back when i made that issue). of course it makes sense to have that be customizable, and in fact i think i might've misread your comment (interpreted it in reverse).
