### ISSUE TITLE
Spec mismatches

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#193]
I am creating WAY to many issues on here, so just bundling them like with #65 (Feature Requests).

SM1: #190 Ripple always comes from the center
SM2: #191 The knob in a switch gets larger when pressed
SM3: The FAB gets smaller when pressed, by default has a shadow, and for colors uses Primary container by default, then Surface, Secondary, and Tertiary as options, with no primary FAB. Also, the sizes in beer css seem a bit off - it looks to me like the beer css extra is the same size as the standard and the beer css large is the same size as small.

**Comment by InsightfulFuture** [comment]
SM4: Shape tokens - #196

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.
