### ISSUE TITLE
Password input with hyperlink or button tag shows icon outside the input

### ISSUE THREAD

**Issue by maxyme-perceiv** [beercss/beercss#195]
Setting the icon in a hyperlink (or button tag) (to allow onclick events) sends the icon outside the input box. 

Example:
`<div class="field label suffix border">
  <input type="password">
  <label>Password</label>
  <a><i>visibility</i></a>
</div>`

https://codepen.io/maxyme/pen/oNQQBBG

**Comment by FirokOtaku** [comment]
Temporary solution: give `<i>` element a `z-index`

```html
<div class="field label suffix border">
  <input type="text">
  <label>Label</label>
  <i onclick="console.log(123)" style="z-index: 100">visibility</i>
</div>
```

**Comment by leonardorafael** [comment]
Try `front` or `back` helpers, to bring elements to front or back, and use `onclick` event.

```
Before
<a><i>visibility</i></a>

After
<i class="front">visibility</i>
```

Seems nice to support another tags inside `field` besides `<i>`.
