### ISSUE TITLE
Would Beer CSS want to merge with Materialize CSS to create one big community and framework?

### ISSUE THREAD

**Issue by nh916** [beercss/beercss#20]
Beer CSS and Materialize CSS are both amazing frameworks that have similar design philosophy and their users and developers love. However, both have a small community and smaller communities generally cannot keep up with the updates of the world. 

It would be a shame if either of these frameworks would diminish forever because they dont have a big enough community to support them. I am thinking since both have similar design philosophy we can combine two small community frameworks to one bigger framework that has a way more developers combined working on it, is more feature rich, and more developers using it and creating issues to improve it. The framework may even be competing with bootstrap, foundation, and bulma in the future. I am wondering if Beer CSS would be willing to combine two small communities and frameworks to one big community for betterment of everyone involved?

**Comment by KicKerBNU** [comment]
Also the Materialize CSS looks abandoned by their owners right now. I hope they return soon to make this dream come true

**Comment by nh916** [comment]
I think the original maintainers of the framework have abandoned it but it has gotten picked up by a small community and they are working hard on it and making lots of progress everyday. Every time I have posted an issue, I have immediately gotten a response by one of the developers.

[https://github.com/materializecss/materialize](https://github.com/materializecss/materialize)

**Comment by laurentpayot** [comment]
- materialize.min.css: 144.5 kB, materialize.min.css.zip: 22.1 kB
- beer.min.css: 57.2 kB, beer.min.css.zip: 10.6kB

Please keep beercss small :pray:

**Comment by nh916** [comment]
Here is the thread inside of materialize CSS where I was asking the community what their thoughts were on combining Beer CSS and Materialize CSS. They seemed to all be very excited if we could make it happen

https://github.com/materializecss/materialize/issues/223

**Comment by leonardorafael** [comment]
Hi guys,

The idea is nice. The two frameworks are awesome. After to read all the discussion here and there, I decided to close this issue for now, ok? The another didscussion was closed today and I agree with that. Feel free to reopen this issue if needed. Cheers 🍺
