### ISSUE TITLE
Menu alignment in parent with scroll

### ISSUE THREAD

**Issue by Rewerson** [beercss/beercss#201]
When the element with drop-down menu is placed in some parent scrollable element, menu itself is activating not in front, and also there is extra space added to the bottom and to the left of the parent element.
Simple example:
![image](https://github.com/beercss/beercss/assets/5984863/bd779426-295b-43de-ad82-796a0130a452)
Code:
```
<article>
  <button>
    <span>Button</span>
    <menu class="active">
      <a>Item 1</a>
      <a>Item 2</a>
      <a>Item 3</a>
    </menu>
  </button>
</article>
<article class='scroll'>
  <button>
    <span>Button</span>
    <menu class="active">
      <a>Item 1</a>
      <a>Item 2</a>
      <a>Item 3</a>
    </menu>
  </button>
</article>
```

**Comment by KicKerBNU** [comment]
Hello @Rewerson, i added a codepen example to make some tests
https://codepen.io/kickerbnu/pen/PoXzzrW

I agree with you the behavior looks wrong, do you have a real case with two dropdowns active at the same time ?

The material deisgn example shows only one dropdown active
https://m3.material.io/components/menus/guidelines

When we have only one dropdown active looks pretty solid.

@leonardorafael @laurentpayot what your toughts about it ?

**Comment by Rewerson** [comment]
Hello @KicKerBNU!
Actually point is not in two active menus, but in strange second of them.
Real case is table in article with clickable cells, menu with some actions on click. When table's container is not scrollable, it's the first case, menu is shown in front and over other elements. But if I add `'scroll'` class to article, there appears some empty space below table, and menu when active is not in front, but underneath article borders, like in second case on my screen.
So problems are: extra space is adding below button, menu is not really visible without additional scrolling.

**Comment by laurentpayot** [comment]
`.scroll` simply adds `overflow: auto`.
@Rewerson You can override this behaviour for your article with:
```css
article.scroll {
  overflow: visible;
}
```
(worked on @KicKerBNU codepen)
Does it do the trick?

**Comment by Rewerson** [comment]
> Does it do the trick?

Not really. In my use case there is also `max-height` of article exists, so in general, `owerflow: auto` is good for it, but when using with menus, it looks strange:
Without scroll:
![image](https://github.com/beercss/beercss/assets/5984863/9b6158b7-0e50-40a8-b197-3fcc12e10203)
With scroll:
![image](https://github.com/beercss/beercss/assets/5984863/529506b9-0fc6-4e61-97b3-936a18e798c0)
I want to achieve that if my table is too long, set article to scrollable, but without additional whitespace on the bottom of arcicle after table, and menus need to appear in front.

**Comment by leonardorafael** [comment]
I think this is a default behavior of CSS.
When you have a parent with `overflow`, all child should not pass it.
But you can try another approach, like:

1) You can add a `<menu>` outside the parent with `overlfow` and control the x/y positions and visibility with JS.
2) You can use the default `<select>` from browser, as a CSS hack.

![image](https://github.com/beercss/beercss/assets/12979016/2099c93f-ab72-4dcc-9266-8cb71edcba1a)

**Comment by Rewerson** [comment]
> I think this is a default behavior of CSS.
> When you have a parent with `overflow`, all child should not pass it.
Got it.
However, your first solution worked for me. Thanks.
I close this issue.
