### ISSUE TITLE
input label overwriting value of field during transition

### ISSUE THREAD

**Issue by guidouil** [beercss/beercss#203]
Hello all,
I love the labels being the placeholder and the transition to the top left of the field on focus,
but on the other side when the field is used for edition purpose and there is already values in it, the content and label are mixed during the transition of the label when showing the field.
I tried to set the class active to the labeled field but it does not remove the transition.
Do you have a workaround or can this be considered as an issue ?
Thanks for your time

**Comment by KicKerBNU** [comment]
Hello @guidouil can you add a Codepen example to help the code reproduction ?

**Comment by leonardorafael** [comment]
Hi, have you tried to add `active` class to `<input>` and `<label>` manually?

https://github.com/beercss/beercss/blob/main/docs/INPUT.md#to-updown-a-label

If you not want to use the **method 2** (placeholder with pure css) try the **method 1** above.
Let me know if this works for you @guidouil

**Comment by guidouil** [comment]
@leonardorafael ok I put the active on the input and the label and everything works perfect. Th e active class on the parent div.field is useless in this case :)
Thank you 😃
