### ISSUE TITLE
Extend FABs size not showing properly

### ISSUE THREAD

**Issue by guidouil** [beercss/beercss#204]
Hello Beers fellows,
I'm experiencing an issue with extended FABs when not shown in medium / default size and the button label is long.
I made a [codepen](https://codepen.io/guidouil/pen/bGOBGXw) to show it.
Am I doing something wrong ?
Thank you and cheers 🍻

**Comment by leonardorafael** [comment]
@guidouil  we don't have size helpers in extended fabs. I will change this issue to an enhancement.

![image](https://github.com/beercss/beercss/assets/12979016/e0844dab-a314-4f9e-bd1f-c0aa9b897283)

**Comment by guidouil** [comment]
I think I was confused with the example in the [documentation](https://github.com/beercss/beercss/blob/main/docs/BUTTON.md#extended-fab-example)
The extra class should not be there 😉
