### ISSUE TITLE
Dropdowns using `details` and `summary` tags?

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#21]
Hi, currently dropdowns can be opened based on their focus status. I'm not sure if that's good for accessibility and it also means all of them are open when using the tab key to move inside the page.
Recently expansions were added using `details` and `summary` html tags (great idea). What are your thoughts on using these tags as well for dropdowns instead of the focus trick? Is it better for accessibility? At least it fixes the automatic opening when focused…

Cheers :beers: 
Laurent

**Comment by laurentpayot** [comment]
Here is a dropdown example with `details`/`summary` I found on the web: https://codepen.io/paulgoetze/pen/bGVoxyj

**Comment by umbundu** [comment]
Greetings,
When you select an item it does not stay selected. How do i do that?
Thanks,
Everardo

**Comment by leonardorafael** [comment]
Hi @umbundu, you can add class "active" to item https://codepen.io/leo-bnu/pen/MWEjvdZ

Hope this helps you 👍

**Comment by umbundu** [comment]
Ola Leonardo,
Muito obrigado pela ajuda.
Um abraco,
Everardo

**Comment by leonardorafael** [comment]
Fixed in v1.3.0

**Comment by umbundu** [comment]
Thanks!
