### ISSUE TITLE
Can I use with React? 

### ISSUE THREAD

**Issue by thedroiddiv** [beercss/beercss#211]
If yes, then how? I am not able to find a way through documentation.

**Comment by ChristianLeicht** [comment]
You should create your own components wrapping the CSS and HTML from the examples.

**Comment by FirokOtaku** [comment]
This is basically a pure CSS lib and could be used at anywhere you want through.

**Comment by thedroiddiv** [comment]
Yeah, I just tried it out. I'll keep this open, if someone wants to document it BTW. If no-one does, I'll do it myself whenever I get the time.

**Comment by leonardorafael** [comment]
Yeah this is just standard CSS, 

I maded a sample with Next.js + React.js here https://codesandbox.io/s/next-js-forked-kgq6r2?file=/index.js (using latest version of Beer 3.4.7)

Hope this helps @thedroiddiv.

**Comment by leonardorafael** [comment]
I will close this issue ok? Feel free to reopen if needed.

**Comment by thedroiddiv** [comment]
Thanks @leonardorafael
