### ISSUE TITLE
Color picker should use the chosen color for itself

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#220]
I was trying out ideas such as changing the font color of the icon and text inside the text field for a color input after user chooses a color. Here is a demo: https://codepen.io/coffeeandwork/pen/OJrwLPV

<img width="312" alt="Screenshot 2023-09-30 at 6 08 03 PM" src="https://github.com/beercss/beercss/assets/6377739/c42a9a35-0362-4506-a7ed-81072ff2521b">

That seemed like it might not work that well because if user chooses white, while the background is white, it wouldn't show, as shown below:

<img width="336" alt="Screenshot 2023-09-30 at 6 08 39 PM" src="https://github.com/beercss/beercss/assets/6377739/76d69c68-29f6-4a05-9faa-a7fa34deaff5">

I was thinking that we could leverage the color theme project that you have in place to use the chosen color, to generate a theme, and apply that theme to the color input field. 

Thoughts?

**Comment by leonardorafael** [comment]
IMO I think we can use the same approach of color picker. We can do that with a little "hack". But could be unclear for devs, that the framework will change the color on `<i>` element. Do we need to do that automatically?

![image](https://github.com/beercss/beercss/assets/12979016/59fa511e-0c54-4447-854e-cfef28e6378b)

![image](https://github.com/beercss/beercss/assets/12979016/ede1e2e7-489d-4c5b-b770-f978981eaa8a)

In Vue (and others) the devs can do that easily, and don't need to change the color of icon always. They can change the color in any element.

![image](https://github.com/beercss/beercss/assets/12979016/d8c4aedf-1f2e-40fb-ba26-915a168bf9aa)

**Comment by coffeeandwork** [comment]
ah ok, I like that idea.
