### ISSUE TITLE
Can't import with NPM on vanilla js project

### ISSUE THREAD

**Issue by Maxouhell** [beercss/beercss#223]
Hi, looks like I can't import this way : 
```
import beercss from "beercss";
import materialDynamicColors from "material-dynamic-colors";
```

got some errors, about import that must start with /, ./ or ../ 👀 

Do you have a working example, without CDN ?

**Comment by leonardorafael** [comment]
I have tested all npm imports here https://github.com/beercss/beercss#npm

Can you give more details about your stack?

Do you install "beercss" and "material-dynamic-colors" before import it?

This error seems to be related when you are importing without installing before.

**Comment by Maxouhell** [comment]
Hi !
It's a simple project, `npm add --save beercss` and `npm add --save material dynamic-colors`

I have them in my node_modules, but can't make the import work 👀

**Comment by leonardorafael** [comment]
I will close this issue, ok? (no response after one week)

**Comment by leonardorafael** [comment]
Oh, I was closing this issue right now, I will reopen it 🙂

**Comment by leonardorafael** [comment]
I would suggest to use a bundler like Vite (https://vitejs.dev/guide/#trying-vite-online), it has a vanilla and vanilla-ts template. 

Why?

With a bundler you can import fonts and other file types automattically. If you start a npm project from zero (without a bundler) you need to implement your own way to import some files types (or use a cdn version instead).

Beer CSS needs to import fonts (.woff2) and (.css) that are in our default import `import 'beercss'`

**Comment by leonardorafael** [comment]
I will update our docs, to suggest use a bundler too (with that simple import).

**Comment by Maxouhell** [comment]
Work perfectly with vite ;)
TY !
