### ISSUE TITLE
Working on material design v3

### ISSUE THREAD

**Issue by leonardorafael** [beercss/beercss#23]
Hi guys,

We want to be scalable and lightweight (~10kb) in terms of material design system. Now we are working on material design v3. Can we handle that? The challenge is do that with a minimal of css (maybe zero of css), whitout breaking changes.

Instructions:
https://material.io/blog/migrating-material-3

Our progress:
https://codepen.io/leo-bnu/pen/yLoxvrL

Good luck for us 🍺

**Comment by laurentpayot** [comment]
Awesome :+1:

**Comment by leonardorafael** [comment]
Hello my friends,

A happy new year for us! I'm very excited with the next release of beercss! I will show some spoilers here.
Hope you enjoy it 😍🍺

### Dynamic colors of material design 3
![hp3LE44RUa](https://user-images.githubusercontent.com/12979016/148377611-a6ecb7b6-1b22-4074-8d0d-65bd182ba679.gif)

### A progress element
![yYbQWKMEOu](https://user-images.githubusercontent.com/12979016/148377631-1da8e204-f4a0-4fc0-befc-285bbe83ad65.gif)

**Comment by laurentpayot** [comment]
Looks great! :smiley: :beers:

**Comment by leonardorafael** [comment]
Released in v2.0.0 🍺🎉

**Comment by laurentpayot** [comment]
Thank you @leonardorafael for all this great work. I will try to do the update this week.
As my drummer from Porto Alegre used to say: Mazaaaah! :beers:
