### ISSUE TITLE
beercss.com dialogs and some spacing not rendering properly on vivo mobile browser 

### ISSUE THREAD

**Issue by shopper360mst** [beercss/beercss#236]
i just found out that beercss is not rendering properly on vivo default mobile browser.
model of my test phone is Vivo YO2s

**Comment by shopper360mst** [comment]
i have checked on the browser capabilities it seems that the browser wasnt able to support css functions like is( )

**Comment by leonardorafael** [comment]
Hi @shopper360mst 

Do the vivo mobile browser exists on play store?
This is the first time that I see an Android phone without Chrome. 
I really don't known how we can provide compatibility to vivo browser without support of `:is` `:not` `--variables`.
I will stay this issue open, maybe the solutions appears.

**Comment by shopper360mst** [comment]
@leonardorafael 

vivo browser doesnt exist in play store. You can try to find an apk in apkpure.com but it wont work without vivo hardware specific as the browser comes pack with plugins like qr scanner and some ad blocker etc.

These phones are made in China specifically for Asian Market. Vivo and Oppo they all have own stock browsers much like Samsung has their Samsung, Xiaomi and Huawei Browser alike.

I've done an extension research on its useragent its running on Chromium below version 90 

to be exact this is the user agent below.

​Mozilla/5.0 (Linux; Android 12; V2221; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36 VivoBrowser/[11.1.0.1](http://11.1.0.1/)

The closest you can experience  this bug; is to download a third party browser called ucBrowser (orange squirrel app logo) and have a go with it.

For start, Ive tried to use a CSS transpiling to help on beer.min.css 
they convert is() selectors into the code below; which works partially, all the dialogs and pages came back to functioning state.
but im still facing some spacing issue. specifically on padding, margins and gaps.

/*this*/
p:is(:first-child, .lead) {
  margin-top: 0;
}

/*transpile into*/
p:-webkit-any(:first-child, .lead) {
  margin-top: 0;
}

p:-moz-any(:first-child, .lead) {
  margin-top: 0;
}

p:is(:first-child, .lead) {
  margin-top: 0;
}

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.
