### ISSUE TITLE
Install Beercss on Ruby on Rails app

### ISSUE THREAD

**Issue by tadeugr** [beercss/beercss#24]
# Motivation

Beercss is awesome. Ruby on Rails is awesome. I've put both together in a Rails app template:

https://railsbytes.com/templates/Vdrs7R 

# Implementation

Create a new Rails app:

```
rails new ror-beercss
```

`cd` to its folder and install Beercss app template:

```
cd ror-beercss
rails app:template LOCATION='https://railsbytes.com/script/Vdrs7R'
```

Create a new controller:

```
rails g controller home index
```

Edit `app/views/layouts/application.html.erb` and add the following HTML code right after `<body>`:

```
<div>
  <div class="tabs">
    <a data-ui="#tab1_" class="active">Tab 1</a>
    <a data-ui="#tab2_">Tab 2</a>
    <a data-ui="#tab3_">Tab 3</a>
  </div>
  <div id="tab1_" class="page padding active">
    <h5>Tab 1</h5>
  </div>
  <div id="tab2_" class="page padding">
    <h5>Tab 2</h5>
  </div>
  <div id="tab3_" class="page padding">
    <h5>Tab 3</h5>
  </div>
</div>
```

Start rails server:

```
rails s
```

Access the app in your browser: http://localhost:3000/home/index

# Results

You should have a boilerplate of Beercss tabs on your page.

**Comment by leonardorafael** [comment]
A really nice work @tadeugr 🍻
