### ISSUE TITLE
`<menu>` and `<li>` better alignment with HTML spec?

### ISSUE THREAD

**Issue by edwindj** [beercss/beercss#240]
One of the attractive features for beercss is that it stays very close to clean HTML.
In general the resulting html is very clean, and beercss styles with a minimal intrusion of class attributes.

Menu's in beercss are very nice. I was wondering if it wouldn't be better if the HTML standard was followed, in which the `menu` items are `<li>` elements. <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu>
Current practice seems to use `<a class="row">` as items, which works fine, but is non-standard html.

**Comment by laurentpayot** [comment]
I also think that replacing sequences of links by `<ul>` lists would be nice. For `<menu>` but also for `<nav>` and everywhere else actually. When I was using Spectre that’s [the way it was implemented](https://picturepan2.github.io/spectre/components/menu.html).
But I don’t know how much it would impact the size of the bundle, in a bad or a good way...

**Comment by leonardorafael** [comment]
We will try to add this on next release, we need to go back to 10 kb (current it's 11 kb)
It's a big challenge.
I will put the next release label to work on it.

**Comment by leonardorafael** [comment]
Hi, the next release we will add support to ol, ul, li inside nav and menu. And the minimalist version of nav and menu will still there.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
https://www.w3schools.com/tags/tag_menu.asp
https://www.w3schools.com/tags/tag_nav.asp
