### ISSUE TITLE
use justify-content flex-start/end instead of start/end

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#244]
For the `justify-content` css property, the values `start` and `end` do not seem to be supported in some opera and android opera browsers as described here: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content according to https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content.

We could replace `start` with `flex-start` and `end` with `flex-end` and there would be no issues with browser support. Thoughts?

**Comment by leonardorafael** [comment]
Merged in https://github.com/beercss/beercss/pull/245
