### ISSUE TITLE
Missing the strong tag in reset.css

### ISSUE THREAD

**Issue by guidouil** [beercss/beercss#250]
Hello Leonardo and beer fellaz,
I'm having an issue because of my markdown rendering.
```html
<article>
  <p><b>This text</b> is bottom aligned</p>
  <p><strong>This text</strong> is NOT bottom aligned</p>
</article>
```

Can you add the strong tag here ?
https://github.com/beercss/beercss/blob/8a6ce3e35de6965decd3c51c6b7c23ea58d5ffc4/src/cdn/helpers/reset.css#L26C7-L26C7 

Thanks

**Comment by leonardorafael** [comment]
I agree

**Comment by leonardorafael** [comment]
Done in v3.4.10 (https://github.com/beercss/beercss/releases/tag/v3.4.10)
