### ISSUE TITLE
Scroll on summaries and full screen search are bad

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#251]
When something happens be it details of summary expanding or keyboard expanding page scrolls down by which point you lose the beginning of content in favor of end. The full screen search experience is fairly broken on mobile.

**Comment by leonardorafael** [comment]
We will close this issue by inactivity, fell free to reopen it.

**Comment by janat08** [comment]
The bad scroll when page expands still happens. I'm unclear what my problems with full screen search were.

**Comment by janat08** [comment]
I can't reopen it myself.

**Comment by leonardorafael** [comment]
Hi @janat08 ,

I will reopen it. But I can't help so much because I didn't understand the issue itself. Can you show more about it? Can you provide a codepen?

At least a codepen, to catch the code and wrong behaviour.

**Comment by janat08** [comment]
Expand summary/details. The page will scroll to bottom of the details. It’s not the desired behavior, as people read from the top and not bottom. https://github.com/beercss/beercss/blob/main/docs/EXPANSION.md

**Comment by janat08** [comment]
If there’s a fix to scroll behavior, I assume that i wanted it to apply to full screen search for when the results list gets rerendered by htmx.

**Comment by leonardorafael** [comment]
I think this is a behavior of browser, we don't have any code to scroll it to up/down, `<summary>/<details>` are just CSS/HTML. Maybe you can add a JS on summary?

```html
<summary onclick="window.scrollTo(0, 0);">...</summary>
```

**Comment by leonardorafael** [comment]
Or you can set a `no-scroll` helper on container `<body class="no-scroll">` or `<main class="no-scroll">` to prevent scroll.

**Comment by janat08** [comment]
Ok then I suppose there’s reason they want you to see bottom so as to not miss it. Must be a no fix.
