### ISSUE TITLE
release v3.4.9 points to v3.4.8

### ISSUE THREAD

**Issue by mxdpeep** [beercss/beercss#252]
release v3.4.9 points to v3.4.8
![image](https://github.com/beercss/beercss/assets/75358/74c21c69-54be-4a2c-aa86-8bacb64f5ac9)

**Comment by leonardorafael** [comment]
It's ok.

After a release, we can update it with some bugfixes, instead to open another release.

**Comment by mxdpeep** [comment]
> It's ok.
> 
> After a release, we can update it with some bug fixes, instead to open another release.

the problem is that the 3.4.9 release is not pointing to 3.4.9 files and you'll download 3.4.8 version

**Comment by leonardorafael** [comment]
Oh now I see. Updated. I usually go to https://github.com/beercss/beercss/tags and get it. Thanks for it.
