### ISSUE TITLE
Dialog doesn't match material specs

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#253]
[Material 3 Web docs dialog](https://material-web.dev/components/dialog/stories/):

![image](https://github.com/beercss/beercss/assets/109481728/6d4306bc-d555-4018-bbfa-582c4b648d41)

BeerCSS Dialog:

![image](https://github.com/beercss/beercss/assets/109481728/9a0935cd-cb10-497b-993e-6e7f3ebee5c7)

**Comment by leonardorafael** [comment]
Done in v3.4.10 (https://github.com/beercss/beercss/releases/tag/v3.4.10)
