### ISSUE TITLE
directional margin and padding

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#255]
We have the following directional css classes for corner rounding of elements:

- `.left-round`
- `.right-round`
- `.top-round`
- `.bottom-round`

Would it make sense to add similar helper classes for margins:

- `.left-margin`
- `.right-margin`
- `.top-margin`
- `.bottom-margin`

and for padding:

- `.left-padding`
- `.right-padding`
- `.top-padding`
- `.bottom-padding`

@leonardorafael I would be happy to implement if this makes sense for the project. Please let me know your thoughts.

**Comment by myrp-leonardo** [comment]
Hi, I guess it's already exists here. 

https://github.com/beercss/beercss/blob/main/docs/HELPERS.md#margins
https://github.com/beercss/beercss/blob/main/docs/HELPERS.md#paddings

I'm using these helpers like this:

```html
<div class="left-padding"></div>
<div class="small-padding left-padding"></div>
<div class="small-padding left-padding top-padding"></div>
<div class="small-padding vertical-padding"></div>
```
