### ISSUE TITLE
Add Chrome 81 and Android 4.4.x support

### ISSUE THREAD

**Issue by Bonzey2416** [beercss/beercss#260]
Can we support Android 4.4.x phones and tablets and Chrome 81? Android 4.4.x devices can update Chrome version to 81. Many people are still using phones and tablets running Android 4.4.x.

**Comment by leonardorafael** [comment]
We can't do that, sorry. Google has discontinued updates on Chrome because the low use of Android KitKat https://groups.google.com/a/chromium.org/g/chromium-dev/c/ypAS49lvN1M/m/LC0OFek5EAAJ

We can support to all systems that can receive browser updates.

In the Chrome 90+ should work.
