### ISSUE TITLE
"ol" and "ul" Regression

### ISSUE THREAD

**Issue by crypnull** [beercss/beercss#262]
I had some "ol" and "ul" lists throughout my page content, in the body, normal text, it looks as the update to add support for "ol" and "ul" broke them in normal page content.

Here is a CodePen, if you change the version back a few versions you can see what I mean.
https://codepen.io/1971562171/pen/abMYNQr

**Comment by leonardorafael** [comment]
Hi @crypnull , this is the default behavior after 3.4.13, to follow the html semantic recommendations we unified `ul`, `ol`, `nav` and `row`. And now they have the same behavior.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
https://www.w3schools.com/tags/tag_menu.asp
https://www.w3schools.com/tags/tag_nav.asp

Release 3.14.3: https://github.com/beercss/beercss/releases/tag/v3.4.13.
Related issue: https://github.com/beercss/beercss/issues/240#issuecomment-1885679855
Codepen: https://codepen.io/leo-bnu/pen/XWGERyO

**Comment by crypnull** [comment]
I see you wrote "add support to ol, ul, li inside nav and menu" but I'm using it outside the nav and menu, just in the page content. A lot of my pages used these.

It's no longer possible to use this basic HTML feature in this framework without hacking it back in myself?

https://www.w3schools.com/html/html_lists.asp

**Comment by leonardorafael** [comment]
If you just want to get the default styles from `ul`, `ol` and `li` do:

```css
ul, ol, li {
  all: revert;
}
```

Otherwise you can add the `vertical` helper on `ol`, or `ul` elements to render a `li` below other.

```html
// to render as vertical
<ul class="vertical">
  <li>1</li>
  <li>2</li>
</ul>

// to render as horizontal
<ul>
  <li>1</li>
  <li>2</li>
</ul>
```

I don't understand what are you trying to do, but I'm trying to help you.
Do you look at the codepen https://codepen.io/leo-bnu/pen/XWGERyO?

**Comment by crypnull** [comment]
The CSS you provided fixed my issue, all I am doing is using ul for a normal list, with bullet points. In the page content, not in any menu.

**Comment by guidouil** [comment]
I have the same issue because list are used in markdown a lo, it should render vertically as default if not inside a nav IMHO. Now I need to have to change the converter to ad vertical class to converted list... and I also agree the horizontal view is what I need inside a nav.

**Comment by leonardorafael** [comment]
In the next release, I will rollback the styles on `<ul>`, `<ol>`, `<li>` (except inside `<menu>` or `<nav>`). I agree the styles on it could be intrusive.

Thanks for feedback!
