### ISSUE TITLE
Allow adding item at the bottom of navrail

### ISSUE THREAD

**Issue by kattschan** [beercss/beercss#277]
Hello, 
I'm a heavy user of Beer CSS and absolutely love it - I just have one thing I wish was in it. When using a navrail, I frequently want to add an item at the bottom(e.g. pages to navigate to at the top, and then a log out button at the very bottom). Is this already possible, and if it's not, is it possible for it to be implemented? For instance, by adding an element with a max class.
Thanks!

**Comment by leonardorafael** [comment]
Hi @kattschan ,

If I understand correctly, you can add itens at bottom/right of navs (rail, drawers, regula nav) adding a item with `max` helper. This helps you?

### Bottom
![image](https://github.com/beercss/beercss/assets/12979016/9d73d35a-7bf8-4f85-8b9b-1a3a66a351ac)

### Right
![image](https://github.com/beercss/beercss/assets/12979016/334699e6-9c39-46b9-8a2c-3cb69489b5ba)

**Comment by kattschan** [comment]
Oh! This is exactly what I meant. I thought I tried this before but I must have done it incorrectly. Thank you!
