### ISSUE TITLE
Dropdown does not work with Safari 

### ISSUE THREAD

**Issue by alaibe** [beercss/beercss#278]
Dropdown does not work with Safari.
Version 17.4 (19618.1.15.11.12)
beercss version: 3.5.1
I simply used:
```
<button>
  <span>Default</span>
  <i>arrow_drop_down</i>
  <menu>
    <a>Item 1</a>
    <a>Item 2</a>
    <a>Item 3</a>
  </menu>
</button>
```

However, i noticed they do work in https://www.beercss.com

**Comment by leonardorafael** [comment]
Hi @alaibe 

This is a limitation of Safari, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

![image](https://github.com/beercss/beercss/assets/12979016/18748e0d-6bf6-426a-b1e2-acd3b701679b)

Also, You can try another the triggers methods here https://github.com/beercss/beercss/blob/main/docs/MENU.md.

Hope this helps.
