### ISSUE TITLE
Material Icons briefly show <i> icon text

### ISSUE THREAD

**Issue by SuperDOS** [beercss/beercss#281]
When loading a page you briefly see the icon text for the materials icon, i noticed in beercss.css it's set to swap instead of block. if I change to font-display:block it won't show the text. very small thing but looks a bit cleaner when loading the page. :)

@font-face {
    font-family: Material Symbols Outlined;
    font-style: normal;
    font-weight: 400;
    font-display: block;
    src: url(material-symbols-outlined.woff2) format("woff2"), url(https://cdn.jsdelivr.net/npm/beercss@3.5.1/dist/cdn/material-symbols-outlined.woff2) format("woff2")
}

@font-face {
    font-family: Material Symbols Rounded;
    font-style: normal;
    font-weight: 400;
    font-display: block;
    src: url(material-symbols-rounded.woff2) format("woff2"), url(https://cdn.jsdelivr.net/npm/beercss@3.5.1/dist/cdn/material-symbols-rounded.woff2) format("woff2")
}

@font-face {
    font-family: Material Symbols Sharp;
    font-style: normal;
    font-weight: 400;
    font-display: block;
    src: url(material-symbols-sharp.woff2) format("woff2"), url(https://cdn.jsdelivr.net/npm/beercss@3.5.1/dist/cdn/material-symbols-sharp.woff2) format("woff2")
}
![image](https://github.com/beercss/beercss/assets/7214952/7bc7873e-70ee-4e7b-8ab1-d06e08380a72)

**Comment by leonardorafael** [comment]
Nice! We will try it and add this on next release.

**Comment by SuperDOS** [comment]
out of curiosity how long before 3.5.2 is released? :)
