### ISSUE TITLE
Menu Component: how to create a multi-level menu ?

### ISSUE THREAD

**Issue by steevepay** [beercss/beercss#283]
Hello, how to create a menu with a child menu? it doesn't seems possible with BeerCSS

<img width="676" alt="menu " src="https://github.com/beercss/beercss/assets/16964532/5a861f76-b996-4722-936a-e4146889ff51">

Picture found on the Material Design 3: [Menu Guidelines](https://m3.material.io/components/menus/guidelines)

**Comment by leonardorafael** [comment]
Hi @steevepay ,

Today this is our best (not exactly what you need):

Discussion: https://github.com/beercss/beercss/discussions/317
Codepen: https://codepen.io/leo-bnu/pen/Baewrgg

**Comment by steevepay** [comment]
Thanks @leonardorafael for the menu expension idea, but that's not a child menu :D

**Comment by leonardorafael** [comment]
Hey @steevepay 
I think we can add something like this on next release (it was very clean) https://codepen.io/leo-bnu/pen/yLWvVLV:

```html
<menu>
  <a>Item</a>
  <a>Item</a>
  <a>More items</a>
  <menu>
    <a>Item</a>
    <a>Item</a>
    <a>More items</a>
    <menu>
      <a>Item</a>
      <a>Item</a>
      <a>More items</a>
    </menu>
  </menu>
</menu>
```

**Comment by steevepay** [comment]
That would be great!
