### ISSUE TITLE
Lists look bad

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#284]
I don't know what it is that is actually wrong with them.  I must've asked the question, but is it really up to spec. I may have been more like considering clickable lists as the proper list for material, but the basic one sometimes has me comparing it against gmail.

**Comment by fabessen** [comment]
Well at least i have to admit that i im not really sure how to style them like in Material 3 documentation:
![image](https://github.com/beercss/beercss/assets/22885059/92cddfa0-876e-4545-ba24-13b3bd8522e6)
https://m3.material.io/components/lists/overview#0519c023-de10-4062-9e4d-4c6918245b1a

Would be really nice if someone could provide a codepen etc. example 🙂👍

**Comment by kennymingt** [comment]
I found that adding `padding` and `no-margin` classes makes them look better. Also `wave` to get the hover effect.
<img width="1040" alt="Screenshot 2024-04-11 at 1 32 12 PM" src="https://github.com/beercss/beercss/assets/9563437/56391632-00d2-4cc5-bd3b-9a9527aff97c">

```
 <div class="padding no-margin row wave">
      <i class="light-green-text">check_circle</i>
      <div class="max"><div>hi</div>Some text here</div>
      <a>
          <i>edit</i>
      </a>
      <a>
          <i>delete</i>
      </a>
  </div>
  <div class="padding no-margin row wave">
      <i class="light-green-text">check_circle</i>
      <div class="max">Some text here</div>
      <a>
          <i>edit</i>
      </a>
      <a>
          <i>delete</i>
      </a>
  </div>
  <div class="padding no-margin row wave">
      <i class="light-green-text">check_circle</i>
      <div class="max">Some text here</div>
      <a>
          <i>edit</i>
      </a>
      <a>
          <i>delete</i>
      </a>
  </div>
```

**Comment by leonardorafael** [comment]
Nice, I will add some examples on next release.
