### ISSUE TITLE
pointer-events: none for :after pseudo

### ISSUE THREAD

**Issue by jsupa** [beercss/beercss#286]
Hi, if I use for example title in .chip it doesn't work but after adding `pointer-events: none` for ::after everything works as it should.

code example
```html
<div class="chip round">
    text
    <i>event</i>
    <p title="13. Apr. 2024 - 05:05">will_expire in 2 days.</p>
</div>
```

**Comment by leonardorafael** [comment]
Hi, for buttons and chips, we don't have access to child elements by default. To enable access to child elements you need to bring the element to front, using `front` helper. Try this:

```html
<div class="chip round">
    text
    <i>event</i>
    <p class="front" title="13. Apr. 2024 - 05:05">will_expire in 2 days.</p>
</div>
```

**Comment by jsupa** [comment]
Hi, yes, thank you, works, I need to read the documentation better 😄
