### ISSUE TITLE
replace forEach() with native for-loops for performance improvement

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#287]
In this benchmark I have tested various looping constructs: https://jsbench.me/dulu7atajk/4. `forEach()` appears slower by an order of magnitude compared to a native for-loop. This makes sense because for each iteration inside `forEach()` we are doing a callback invocation that comes with its extra costs that we don't incur with a native for loop.

**Comment by leonardorafael** [comment]
Hi @coffeeandwork , there are something wrong here, I published a js perf here (https://jsperf.app/tecele) and get some results. I always understood that the native for loop is the fastest but, why these results?

### Chrome 123 (3 runs)
![go001](https://github.com/beercss/beercss/assets/12979016/96b7f4dc-00d3-4507-806e-84277afa5247)
![go002](https://github.com/beercss/beercss/assets/12979016/fd87f398-32e9-4968-8866-c2b0ab5d6f9a)
![go003](https://github.com/beercss/beercss/assets/12979016/94586550-6468-42eb-b051-95e784c2c48b)

### Firefox 124 (3 runs)
![ff001](https://github.com/beercss/beercss/assets/12979016/9f00d4f4-08c0-4df1-9a25-be525805b359)
![ff002](https://github.com/beercss/beercss/assets/12979016/9238824a-7d6e-4eab-bfb0-8057299f9326)
![ff003](https://github.com/beercss/beercss/assets/12979016/491f89df-0c11-494a-a977-32c31b110564)

**Comment by leonardorafael** [comment]
I believe that modern browsers can do some performance trick here. 🪄

**Comment by coffeeandwork** [comment]
I think it's more likely that the `console.log()` is computationally expensive and is overshadowing the relatively smaller difference in the performance of `forEach` vs native for-loop. I have modified your jsperf slight and I was able to get a consistent result of the native for-loop being way faster than `forEach`: https://jsperf.app/tecele/2 Let me know if you are seeing something different.

**Comment by leonardorafael** [comment]
Nice!

**Comment by leonardorafael** [comment]
To be fair I removed all content inside loop. The forEach is 10x slower than others. Seems good to change it. The best perfomance isn't the most readable, but it's ok.

![image](https://github.com/beercss/beercss/assets/12979016/73a5e2a9-89db-45ad-92af-3c87df8e3ac0)
