### ISSUE TITLE
Material Design 3 Dynamic colors script

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#29]
Looks like moving to Material Design 3 was a lot of work. Kudos for that! :clap: 
I was really impressed by the dynamic colors feature on the beercss site :open_mouth: 

@leonardorafael If I’m right you are using a [script](https://github.com/beercss/beercss/blob/1b72df1d62b19be5df4cd484e4064dd01ae23e58/src/app.html#L21) from the [Material theme builder](https://material-foundation.github.io/material-theme-builder/). Did you find documentation somewhere or did you reverse-engineered it? Can you tell us how to use it?

**Comment by leonardorafael** [comment]
Hey @laurentpayot 

Yes we loaded that script (a compiled and heavy script) and call the functions. I do not find a documentation for that yet.

**Comment by laurentpayot** [comment]
I see. Well done :+1: 

For those interested, if you visit https://material-foundation.github.io/material-theme-builder/ and write the following code in your JS console you will get the light theme values for a pure red color (for instance):
```js
console.table(module$exports$google3$ux$material$theme_generator$src$theme$index$ThemeAdapter$fromColor("#FF0000").light)
```
