### ISSUE TITLE
Feature request: Allow for indeterminate checkboxes

### ISSUE THREAD

**Issue by cesar-perceiv** [beercss/beercss#295]
Hello there,

Thanks for this awesome library!

Small feature request: It would be great to support indeterminate checkboxes:
<img width="30" alt="image" src="https://github.com/beercss/beercss/assets/66697776/dc759d3f-636a-42d4-9e5e-5a0ebd0c8756">
Material UI ref: https://mui.com/material-ui/react-checkbox/#indeterminate

Thanks!

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v3.5.3
