### ISSUE TITLE
The `auto-padding` class should not exist

### ISSUE THREAD

**Issue by jonasgeiler** [beercss/beercss#296]
There is no `auto` value for `padding` in CSS, only for `margin`.

The class is defined here:
https://github.com/beercss/beercss/blob/15104221584466af436a09a817be80865e1d444c/src/cdn/helpers/paddings.css#L13-L15

And here is the `padding` syntax description from MDN:
https://developer.mozilla.org/docs/Web/CSS/padding#syntax

**Comment by leonardorafael** [comment]
True
