### ISSUE TITLE
Autoresize textarea with max height

### ISSUE THREAD

**Issue by SuperDOS** [beercss/beercss#297]
I tried the newly added min attribute for textarea but wonder if it's possible to combine somehow with a max height so it can't expand further but have a scrollbar?

also when setting a value to the textarea it won't expand until you click it and press enter.
`document.getElementById('DemoTextarea').value = "demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext demotext";`

**Comment by leonardorafael** [comment]
Hi @SuperDOS ,

Unfortunately set a `value` from textarea directly from JS will not work, because we can't detect the change on JS to resize it. But, you can use `innerHTML` or `textContent`. This will change the DOM and do the job automatically. Other way is to call `ui()` function after set the `value` of textarea.

**Method 1**
```js
document.getElementById('DemoTextarea').innerHTML = "...";
```

**Method 2**
```js
document.getElementById('DemoTextarea').textContent = "...";
```

**Method 3**
```js
document.getElementById('DemoTextarea').value= "...";
ui();
```

Hope this helps!

**Comment by SuperDOS** [comment]
@leonardorafael  Thanks that works!
Had another question if it's possible to combine min somehow with a max height so it can't expand further than let's say 250px but scrollable?

**Comment by leonardorafael** [comment]
Humm, we don't have anything like that today. But in future, I guess we can combine with existent helpers like `small-height`, `medium-height`, `large-height` like:

```html
<div class="field border label textarea min small-height">
   <...></...>
</div>
```

**Comment by SuperDOS** [comment]
have you considered adding this in the future? right now I solve it by adding a custom css with  max-height: 250px; on the input. if not go ahead and close this :) thanks
