### ISSUE TITLE
External assets being used when using beercss as a NPM package.

### ISSUE THREAD

**Issue by WardPearce** [beercss/beercss#298]
https://github.com/WardPearce/Materialious/issues/173

**Comment by leonardorafael** [comment]
@WardPearce nice project!

https://github.com/beercss/beercss/blob/main/src/cdn/settings/fonts.css

As you can see, the external url is just a font fallback when the local font fails (it's highly recommended to have a font fallback). The modern bundlers should put the local fonts on the right path automatically.

Just verify if the bundler is copying the fonts on the right path. If not, do that mannually.
