### ISSUE TITLE
https://www.beercss.com/ is down

### ISSUE THREAD

**Issue by wptheme4me** [beercss/beercss#301]
Hey, not sure where to write, but for information https://www.beercss.com/ is down; 
cdn.jsdelivr.net/npm/beercss - do not work as well.

**Comment by KicKerBNU** [comment]
Its working for me.

**Comment by wptheme4me** [comment]
Yes, it works now. It seems where were temporary issue. Thank you.

**Comment by wptheme4me** [comment]
-
