### ISSUE TITLE
Number input counting when tapping on mobile

### ISSUE THREAD

**Issue by iCornflakes** [beercss/beercss#306]
Instead of allowing number input the element starts counting upwards/downwards when clicking on it. 
Happens only on mobile, desktop works fine.
Tested browsers: Google chrome (Desktop), Chrome (Mobile), Vivaldi(Desktop) and Samsung Browser(Mobile) 
Mobile device: Samsung Galaxy S24

[numbers-2024-05-11_22.50.11.webm](https://github.com/beercss/beercss/assets/7988840/b94ec72b-0531-4667-b003-588994c6f94e)

PS: love beercss just some bugs getting in my way right now, nice work keep it up!

**Comment by KicKerBNU** [comment]
Can you give us more information regarding your device ? I'm testing with iOS and can't reproduce it.

**Comment by iCornflakes** [comment]
> Can you give us more information regarding your device ? I'm testing with iOS and can't reproduce it.

yep just added, sry

**Comment by iCornflakes** [comment]
On Firefox Desktop the clicking doesnt trigger a count up/down, just scrolling within the box does. Not sure if thats intended see screenshot:

![image](https://github.com/beercss/beercss/assets/7988840/0ac8fc05-7c74-408c-bb3f-fee3aa8b2f00)

Mobile Firefox actually works flawlessly, no bugs there and opens the number only keyboard just fine.

**Comment by iCornflakes** [comment]
Seems like removing  `input::-webkit-inner-spin-button, input::-webkit-outer-spin-button` from:

```
input[type=file], input[type=color], :not(.field) > input[type^=date], :not(.field) > input[type^=time], input::-webkit-inner-spin-button, input::-webkit-outer-spin-button, input::-webkit-calendar-picker-indicator {
    opacity: 0;
    position: absolute;
    inset: 0;
    inline-size: 100%;
    block-size: 100%;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    z-index: 2 !important
}
```
fixes that. Atleast that is my temporary workaround for it.
Also I've just added the standard css to hide the pseudo elements, after that and everything looks just fine.
```

/* Source: https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp */
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```
The scrolling behaviour is a normal thing for number inputs, I've just not recognized it before.

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v3.5.6 and feel free to reopen this issue.
