### ISSUE TITLE
Slider tooltip not showing/buggy behaviour on mobile

### ISSUE THREAD

**Issue by iCornflakes** [beercss/beercss#307]
The slider doesnt show any tooltip. Sometime it does work tho, but with buggy behaviour. Spam clicking works on real mobile while in browser it rarely does. 
The range slider works better than the others but still buggy. This behaviour has also been tested on another android device from a friend who tried my app, no tooltips as well.
Happens only on mobile, desktop works fine.

Tested browsers: Google chrome (Desktop), Chrome (Mobile), Vivaldi(Desktop) and Samsung Browser(Mobile)
Mobile device: Samsung Galaxy S24

[sliders-2024-05-11_23.01.22.webm](https://github.com/beercss/beercss/assets/7988840/9031fa0d-f3cf-456b-9586-b1ae62c6ea69)

EDIT: Firefox on desktop in mobile mode seems to work just fine, mobile still a bit buggy only when trying to move the pointer element

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v3.5.6 and feel free to reopen this issue.
