### ISSUE TITLE
Round button applying extra space

### ISSUE THREAD

**Issue by KicKerBNU** [beercss/beercss#31]
Hello again, 

I found this behavior using round buttons

![image](https://user-images.githubusercontent.com/43939417/150699440-0471ec0c-9bb0-48d8-a3fd-edcd3ffd4203.png)

Inspecting element i can see that `transform: none` is applying some aditional space, that should happen ?

Made some codepen to help the analysis:
https://codepen.io/kickerbnu/pen/vYWBEWJ

**Comment by leonardorafael** [comment]
Hey @KicKerBNU ,

We have `center` and `center-align` helpers. `center` is for positions and `center-align` is for alignments. 

The `center` that you used in your example is for position and can be used in absolute or fixed elements.

Use `center-align` in a parent element to align all child elements to center. You always need to apply the `*-align` helper in a parent element.

Maybe we need to update our "documentation" to be more understandable...

**Comment by KicKerBNU** [comment]
Perfect, thanks for the help, hope this issue help some one with the same misunderstanding in the future
