### ISSUE TITLE
Menu inside list item breaks

### ISSUE THREAD

**Issue by thdoan** [beercss/beercss#310]
Is this a bug, or am I doing something wrong?

```
  <a class="row padding surface-container wave">
    <div class="max">
      <h6 class="small">Headline</h6>
    </div>
    <button class="front circle transparent">
      <i>more_vert</i>
      <menu class="left no-wrap">
        <a>Item 1</a>
        <a>Item 2</a>
        <a>Item 3</a>
      </menu>
    </button>
  </a>
```

The menu isn't supposed to break outside of the list item. What's interesting is if you manually add the `<menu>` through DOM inspector then it works.

Test file is attached.

[beer_test.zip](https://github.com/beercss/beercss/files/15387455/beer_test.zip)

**Comment by leonardorafael** [comment]
Hi @thdoan ,

This is an ilegal HTML markup https://www.w3.org/TR/html401/struct/links.html#h-12.2.2 where says "Links and anchors defined by the A element must not be nested; an A element must not contain any other A elements.". This is a browser behavior.

Try replace the `<a class="row"` to `<div class="row"`. 👍

**Comment by thdoan** [comment]
Thanks, that works.
