### ISSUE TITLE
Menu inside div.row with wave class disables menu

### ISSUE THREAD

**Issue by jasonbouffard** [beercss/beercss#315]
Please see codepen here: https://codepen.io/Jason-Bouffard/pen/VwObjow
First row's menu works.
Second row's menu with the wave class does not.

**Comment by leonardorafael** [comment]
Hi @jasonbouffard ,

The main idea of `wave` helper is to have an element clicakable (and no other child element clickable). But, If you want clickable elements inside it use `front` helper on child element. So you can do `<button class="front">` on your code.

👍?

**Comment by leonardorafael** [comment]
It's not nice to use the `wave` helper in your case. I would to sugest to create a `hover` helper then (maybe we can add this helper on next version):

```css
.hover:hover {
  background: var(--active);
}
```

```html
<div class="row hover">
```

So you can remove the `wave` and `front` helpers from your code.

**Comment by jasonbouffard** [comment]
You’re right! Would definitely vote yes to have a hover helper. Thanks for
the beercss!
