### ISSUE TITLE
Not an Issue But Just a message

### ISSUE THREAD

**Issue by UdayKiranPadhy** [beercss/beercss#319]
I really like the concept of focusing on DX and the work. I could not find any convey this message to you guys , so writing this in an issue 😄 . 

Initially I wanted to create a web page using m3 and came across https://material-web.dev/about/intro/ . Later after a bit research googling i found your amazing Osome page https://www.beercss.com/ . I initially felt like its similar to bootstarp library but following m3 design . But when i was developing my project I felt i am wrong and much more powerful than i thought .

Also like the way in which you are sharing the raw Html instead of packing it in a React Component and exposing options as props . 

Once my works are done will try to contribute back here .

Few Notes :- 
1. Your Code pin collection (https://codepen.io/collection/XydYMB?cursor=eyJwYWdlIjoxfQ==) is not that visible to the world , i was able to find this helpful resource after 2 hrs long trying to understand how to use beercss . 
2. I think this repo could be more visible to the world by implementing other web components which the m3 doesnt provide / will not provide for web. such as Nav Bar (https://m3.material.io/)
<img width="1237" alt="Screenshot 2024-06-21 at 2 49 10 AM" src="https://github.com/beercss/beercss/assets/58071209/013a5643-b022-4075-bc31-d9b4f520e1c0">
3. There are many components which Google doesnt share for web and for now they are not even developing and went under maintaince so i feel that this project has the potential to fill the gap. 

Feel free to close this issue after you read this . Its not an issue 😄  .

Thanks for the project .
Cheers .

**Comment by leonardorafael** [comment]
Hi @UdayKiranPadhy 

Thanks for the feedback, we are trying to deliver the best experience on code, mixing semantic html with some global helpers.

I guess we can combine some elements and helpers to achieve this component too (and publish this on our homepage).

All best 🍻
