### ISSUE TITLE
Alignment the p tag with a span tag

### ISSUE THREAD

**Issue by KicKerBNU** [beercss/beercss#32]
When we use **p** tag with an **span** the alignment of span is not the same of **p**.

Should we have the same alignment ? My workaround here was using a `display: contents` for the **span** tag
**![image](https://user-images.githubusercontent.com/43939417/150701204-3cedcdbb-3546-49af-ac26-0929aa61650f.png)**

Codepen example below:
https://codepen.io/kickerbnu/pen/KKyPpPP

**Comment by leonardorafael** [comment]
Hey @KicKerBNU ,

We have `center` and `center-align` helpers. `center` is for positions and `center-align` is for alignments. 

The `center` that you used in your example is for position and can be used in absolute or fixed elements.

Use center-align in a parent element to align all child elements to center. You always need to apply the `*-align` helper in a parent element.

Maybe we need to update our "documentation" to be more understandable...

**Comment by leonardorafael** [comment]
Hi,

Fixed in v2.0.2 https://github.com/beercss/beercss/releases/tag/v2.0.2
