### ISSUE TITLE
Slider cannot be changed programmatically

### ISSUE THREAD

**Issue by kattschan** [beercss/beercss#321]
When I attempt to change the value of a slider programatically(for example, in a music player), part of it updates and part of it does not. I have attached a video of the issue in action. The code for this is:

```
  const duration = document.getElementById("duration");
  duration.max = audio.duration;
  audio.addEventListener("timeupdate", () => {
    duration.value = audio.currentTime;
  });
```

Great project!
https://github.com/beercss/beercss/assets/111166669/62b4cc3d-9486-4f0d-b9ce-aab2780f36b6

**Comment by KicKerBNU** [comment]
Hello @kattschan i made some tests here:

https://codepen.io/kickerbnu/pen/MWdGMoE

the Slider looks okay for me, maybe you have some issue with the logic to track the audio. 
I hope this codepen helps you. 🍺 

Credits: tasmagirl [https://codepen.io/tasmagirl/pen/jOoVxKN](url)

**Comment by leonardorafael** [comment]
@kattschan in your case, you need to call the `ui()` function to update the slider, because when you change the value by JS, it doesn't updates the DOM (except if you are using a JS framework).

Try this:
https://codepen.io/leo-bnu/pen/MWdGNoZ

**Comment by kattschan** [comment]
That makes sense! I normally use a framework but I'm writing a desktop app with Tauri, so I've never encountered this before. Running `ui()` like you suggested works great, the only problem remaining is that the slider _really_ doesn't like it when you drag it. Clicking is fine, but if you drag it the audio skips around seemingly at random and oftentimes appears to keep playing but has stopped playing in the page. Is there any insight to this? This is probably an issue with my script's logic. This `play` function runs when the user clicks the play button above:
```js
async function play() {
  const contents = await readFile("test.mp3", { baseDir: BaseDirectory.Audio });
  console.debug("read file");
  const blob = new Blob([contents], { type: "audio/mpeg" });
  console.debug("created blob");
  const url = URL.createObjectURL(blob);
  console.debug("created url");
  const audio = new Audio(url);
  console.debug("created audio");
  document.body.appendChild(audio);
  document.querySelector("audio").controls = true;
  console.debug("appended audio");
  audio.play();
  audio.addEventListener("timeupdate", () => {
    duration.value = audio.currentTime;
    ui();
    duration.max = Math.floor(audio.duration);
    ui();
  });
}
```
and the input part of the slider is:
```html
          <input
            type="range"
            id="duration"
            oninput="document.querySelector('audio').currentTime = this.value;"
          />
```
Thanks again!

https://github.com/beercss/beercss/assets/111166669/091cf803-6264-4dcd-bc36-90d949f1423f
