### ISSUE TITLE
Select's option text gets selected 

### ISSUE THREAD

**Issue by art-solopov** [beercss/beercss#324]
After picking an option in a select, after a while the text inside the select gets selected.
Reproduced in Firefox 126 on Linux. Doesn't reproduce in Chromium 126 on Linux.

![изображение](https://github.com/beercss/beercss/assets/5079987/0f7c916a-edea-416e-b1da-569b6c10de0e)

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v3.6.4, thanks for the catch 🍺

**Comment by leonardorafael** [comment]
No work as expexted, I will reopen to fix another time

**Comment by LIGMATV** [comment]
> The `user-select: none` property not work as expected on Firefox. I will reopen to fix another time.

Just use `-moz-user-select: -moz-none`, it will work in Firefox.

**Comment by leonardorafael** [comment]
Now it's ok, fixed on https://github.com/beercss/beercss/releases/tag/v3.6.5
