### ISSUE TITLE
Copy Button, Select Menu UI, and Multiple Selection

### ISSUE THREAD

**Issue by LIGMATV** [beercss/beercss#326]
Copy Button like in [clipboard.js](https://clipboardjs.com/) should be cool, the [selects](https://www.beercss.com/#selects) should be have UI like in [menus](https://www.beercss.com/#menus), like in [Material Angular](https://material.angular.io/components/select/overview), and also multiple selection like in [Material Angular](https://material.angular.io/components/select/overview#multiple-selection).

**Comment by leonardorafael** [comment]
Hi @LIGMATV ,

I think we already can handle that, See our "Reddit Template" https://www.beercss.com/reddit

### Select Menu UI
![image](https://github.com/beercss/beercss/assets/12979016/ae18204f-b71e-432d-93bc-e2ba73ed6ba5)
![image](https://github.com/beercss/beercss/assets/12979016/9dbc611c-f8b0-47af-a93f-7f45e08e46bc)

### Multiple Selection
In this example we add switches, but you can add checkboxes too:

![image](https://github.com/beercss/beercss/assets/12979016/8c7daf90-5b65-47fc-94fa-d59128d65f5f)

### Copy Button
I think the browsers already have an API for clipboard. But I never used it before 😅.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by LIGMATV** [comment]
> Hi @LIGMATV ,
> 
> I think we already can handle that. See our "Reddit Template" https://www.beercss.com/reddit
> 
> ### Select Menu UI
> ![image](https://private-user-images.githubusercontent.com/12979016/344501467-ae18204f-b71e-432d-93bc-e2ba73ed6ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDc4MzIsIm5iZiI6MTcxOTgwNzUzMiwicGF0aCI6Ii8xMjk3OTAxNi8zNDQ1MDE0NjctYWUxODIwNGYtYjcxZS00MzJkLTkzYmMtZTJiYTczZWQ2YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA0MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmI3OGEwNGM4ODczODgzNWQyODM1ZjYyZDc4MTNjZTAwZTgzNWM3MjQzZjNmYTk4MGE3MzE3ZmZkYjdiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ORanoAtlf7PYg3YdR5zJZF4iPb0jLrFKYcxNuKO62vw) ![image](https://private-user-images.githubusercontent.com/12979016/344501434-9dbc611c-f8b0-47af-a93f-7f45e08e46bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDc4MzIsIm5iZiI6MTcxOTgwNzUzMiwicGF0aCI6Ii8xMjk3OTAxNi8zNDQ1MDE0MzQtOWRiYzYxMWMtZjhiMC00N2FmLWE5M2YtN2Y0NWUwOGU0NmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA0MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MTYwMzliMGEzNTAzYTU3ODBmNzcxYmRiMGIxZThhM2QxN2EzNTA0M2U4YTk2YzJhYjU1NjBkYTJmZThkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZZCMJTb3qGICvr1PC71Y3wcvqzBLwA54lpdH-RAqI8)
> 
> ### Multiple Selection
> In this example we add switches, but you can add checkboxes too:
> 
> ![image](https://private-user-images.githubusercontent.com/12979016/344501495-8c7daf90-5b65-47fc-94fa-d59128d65f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDc4MzIsIm5iZiI6MTcxOTgwNzUzMiwicGF0aCI6Ii8xMjk3OTAxNi8zNDQ1MDE0OTUtOGM3ZGFmOTAtNWI2NS00N2ZjLTk0ZmEtZDU5MTI4ZDY1ZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA0MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjFkNmQ1MDc4MDhmMmI4NWFjZTk0NjM3NzFlMDRjMTAzZGE1ZjkxMjY1MzgxMTYzNWQ0MTFjZjZkZDY5MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHWOHzPMKaCRkqFtfvVTbl9QRGtpNEDBAaVriSnjsrM)
> 
> ### Copy Button
> I think the browsers already have an API for clipboard. But I never used it before 😅.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
> 
> Hope this helps

Ah, not know about before, but i just want to edit my issue to remove the clipboard.js but your response so fast. It fine now, thanks.
