### ISSUE TITLE
Date picker alignement on iOS

### ISSUE THREAD

**Issue by guidouil** [beercss/beercss#330]
Ciao Leonardo,
I just found out that the date and time picker shows the content as centered on iOS on iPhone.
SInce most of other fields are left aligned it feels wrong.
Can you do something about it ?
Cheers 🍻

![image](https://github.com/beercss/beercss/assets/594367/67b09b66-13f4-411f-b9b2-1955d9384a8c)

**Comment by leonardorafael** [comment]
Hi @guidouil 

This is related to an iOS 15 update https://forums.developer.apple.com/forums/thread/691305

[Done in v3.6.6](https://github.com/beercss/beercss/releases/tag/v3.6.6)
