### ISSUE TITLE
Input label display after browser autocomplete

### ISSUE THREAD

**Issue by wgehner** [beercss/beercss#332]
When using autocomplete for input fields, the Chrome browser sets the the pseudo class -internal-autofill-selected that has a light blue background. The beer-css label does not work with the background. See screenshot: 
 
![backgroundOnBrowserAutocomplete](https://github.com/user-attachments/assets/66ab3124-472e-401a-b462-a8fa55b40703)

**Comment by wgehner** [comment]
No more white background on the 'fieldset', but I get black text on Chrome after autocomplete 

![chrome_ios](https://github.com/user-attachments/assets/feab3a7b-a399-4f0e-8551-f13ad0855dd1)

now with 3.6.9 as shown

**Comment by leonardorafael** [comment]
Oh, we forgot to change the color text too 😞
