### ISSUE TITLE
Progress does not show inside a loading button

### ISSUE THREAD

**Issue by wgehner** [beercss/beercss#334]
Trying to implement a loading button as follows

```
      <button>
            <span>
                <i>login</i>Register
            </span>
            <progress class="circle" style="display:block"></progress>
      </button>
```
The Circle doesn't show, see screenshot. I would typically hide the span while the circle shows.

![loadingButton](https://github.com/user-attachments/assets/12e8a04a-0e7c-4ae6-a72d-824406c135c4)

**Comment by leonardorafael** [comment]
Hi @wgehner 

This is the corret markup. You need to set a color and size helpers (`white-text` and `smalll`) to best fit:

```
<button>
  <i>login</i>
  <span>Register</span>
  <progress class="circle white-text small"></progress>
</button>
```

**Comment by wgehner** [comment]
Thank you, that worked! Closing.
