### ISSUE TITLE
Menu not working with touch

### ISSUE THREAD

**Issue by samueller** [beercss/beercss#337]
The top-left menu (hamburger menu) on my homepage works great with a mouse:
https://scott.am/

However, when I touch the hamburger menu icon on my phone, the menu doesn't appear. Do I need to do something special to enable touch? I simply have the following code:
```html
<button class="circle transparent">
        <i>menu</i>
        <menu class="no-wrap">
                <a href="/">Home</a>
                <a href="#info">Contact</a>
                <a href="#about">About</a>
                <a href="#publications">Publications</a>
                <a href="#teaching">Teaching</a>
                <a href="#cv">CV</a>
        </menu>
</button>
```

**Comment by leonardorafael** [comment]
Hi @samueller ,

It seems Apple (webkit) doesn't play well with `:focus-whitin` CSS selector. 
All browsers in Apple systems uses the webkit engine as core, so this will happen in all browsers.
You can use the `data-ui` approach instead the pure CSS approach.
Here are some discussion about https://github.com/beercss/beercss/issues/85#issuecomment-1264152575

**Comment by leonardorafael** [comment]
@samueller ,

The link that I posted, was from a old markup. I will close this issue now.
