### ISSUE TITLE
safe-area-insert-top etc breaks layout

### ISSUE THREAD

**Issue by wgehner** [beercss/beercss#338]
Has anyone reliably applied safe areas for mobile phone apps, so a beer.css app doesn't bleed into the front camera etc? I tried

```
body {
    margin-top: env(safe-area-inset-top) !important;
    margin-left: env(safe-area-inset-left) !important;
    margin-bottom: env(safe-area-inset-bottom) !important;
    margin-right: env(safe-area-inset-right) !important;
}
```
but it's not as simple as that. See screenshot attached. It also makes the main area scroll vertically.
![20240720_134551](https://github.com/user-attachments/assets/0ced10cc-6000-43a7-8c27-6137e6fa2f74)

**Comment by wgehner** [comment]
Bump. It seems material :-) that beercss would work on phone apps that use HTML, e.g. when using Capacitor.

**Comment by leonardorafael** [comment]
Hi @wgehner,

Sorry, but I can't reproduce this issue. Have you test our homepage? I tested on real devices and emulators and it seems ok.

### Real iPhone 12 iOS 17.x + Chrome
![WhatsApp Image 2024-07-25 at 18 51 49](https://github.com/user-attachments/assets/2fdc2db6-e5b3-4210-a854-4fdb3c644778)

### iPhone 12 + iOS 17.x + Safari
![beer-003](https://github.com/user-attachments/assets/42022419-87df-4a06-b991-aeda409ba719)

### iPhone 12 + iOS 14.x + Safari
![beer-002](https://github.com/user-attachments/assets/ea140b07-921b-4fe7-87db-813d14149437)

### Real Xiaomi + Android 14 + Chrome
![WhatsApp Image 2024-07-25 at 18 51 57](https://github.com/user-attachments/assets/d4b41dc1-cc81-4f42-87c4-96c72f91233c)

**Comment by wgehner** [comment]
Hi @leonardorafael ,

Emulators don't show it. They don't seem to use the WebKit WebView that ios uses inside capacitor apps to render HTML.

See https://github.com/wgehner/beercss-in-app to reproduce. This demo app has the default beercss HTML.

**Comment by wgehner** [comment]
Looking great in in 3.6.9, thank you!
