### ISSUE TITLE
Need small help!

### ISSUE THREAD

**Issue by bubnenkoff** [beercss/beercss#34]
Hello! Big thanks for your work!
Could you shoe me how to align names and buttons on the same level?
Like:
![изображение](https://user-images.githubusercontent.com/6514326/152031205-0fb37970-f4f4-47ab-b8d2-d8feb8b721b9.png)

https://codepen.io/bubnenkoff/pen/KKyzWOa

**Comment by leonardorafael** [comment]
Hi!

When you use `<h*>` elements you need to use `no-margin` helper because they have default margins that can affect the alignment. And you can use the `middle-align` to align vertical and the `center-align` to align horizontal. Try the code below:

```
<nav class="middle-align center-align">
  <h6 class="no-margin">Name1</h6>
  <button>foo</button>
  <span>text</span>                      
  <h6 class="no-margin">Name2</h6>
  <button>bar</button>
  <span>text</span>                    
</nav>
```

**Comment by bubnenkoff** [comment]
Bit thanks!
Could you add more docs about helpers?

Maybe it's obvious for devs who use HTML/CSS every day, but I am who use it time to time for some trivial tasks.

**Comment by bubnenkoff** [comment]
And could I do what I want if every element is placed in own div (for example I want encapsulate is to make padding\coloring)?
```
<nav class="center-align">
  <div style="SomeMyStyleForThisDiv">
  <h6 class="no-margin">Name1</h6>
  <button>foo</button>
  <span>text</span> 
   </div>
  <div style="SomeMyStyleForThisDiv">
  <h6 class="no-margin">Name2</h6>
  <button>bar</button>
  <span>text</span>                    
  </div>
</nav>
```

**Comment by leonardorafael** [comment]
I think you can get the same initial result using `middle-align` on that divs. If you need to encapsulate, try this:

```
<nav class="center-align">

  <div class="middle-align" style="SomeMyStyleForThisDiv">
    <h6 class="no-margin">Name1</h6>
    <button>foo</button>
    <span>text</span>
  </div>

  <div class="middle-align" style="SomeMyStyleForThisDiv">
    <h6 class="no-margin">Name2</h6>
    <button>bar</button>
    <span>text</span>
  </div>

</nav>
``` 

![152031205-0fb37970-f4f4-47ab-b8d2-d8feb8b721b9](https://user-images.githubusercontent.com/12979016/152142312-8dd356f1-cb43-4ff9-9f5b-151fe844abb6.png)

**Comment by bubnenkoff** [comment]
Oh really big thanks for your help and your work!
