### ISSUE TITLE
Links on CSS floats not working

### ISSUE THREAD

**Issue by samueller** [beercss/beercss#340]
Do I need to do anything special for `float`ing `<section>`s in Beer CSS? None of the links are clickable on the right side of my site:
https://scott.am

When I delete the following `<link>` to `beer.min.css`, the `<section>` with `float: right` works perfect:
```html
<link href="https://cdn.jsdelivr.net/npm/beercss@3.6.8/dist/cdn/beer.min.css" rel="stylesheet">
```

Of course, the whole page is then ugly.

**Comment by leonardorafael** [comment]
Hi @samueller ,

If you choose to use a `float` stying is recommend to do a "clear float" method, https://www.w3schools.com/howto/howto_css_clearfix.asp

If you add a `overflow: auto` to `<section>` (and remove the `max-width` from `<main>`), you will get something like this:

![image](https://github.com/user-attachments/assets/d58493fb-18ed-4d14-acdd-5dd1550aa4a0)

Hope this helps.

**Comment by samueller** [comment]
> Hi @samueller ,
> 
> I think this is more related to CSS itself.

Beer CSS is doing something that prevents links on the `float` from working because removing `beer.min.css` fixes it.

> If you add a `overflow: auto` to all `<section>` (and remove the `max-width` from `<main>`)

But this doesn't allow the text to flow around the profile photo/info `<section>`.

**Comment by samueller** [comment]
Fixed issue with links in floating `<section>` by simply assigning `z-index: 1` to that `<section>` in CSS. Still unsure why I needed that with Beer CSS (works fine without that `z-index` setting when removing `beer.min.css`).

**Comment by leonardorafael** [comment]
Yep this is very strange, I was doing a codepen with this and seems right https://codepen.io/leo-bnu/pen/WNqxPNy
I will try a little more to discover this later.

**Comment by leonardorafael** [comment]
I think instead manually set a `float: right` to `<section>` we can implement this on Beer CSS using `<aside>` tag.

Something like `<aside class="right">` or `<aside class="left">`.

LGTM, but we need to think more about it in future.
