### ISSUE TITLE
disabled <textarea> field, autosize not working

### ISSUE THREAD

**Issue by edwindj** [beercss/beercss#348]
Currently a disabled textarea field is not autosizing:
So, the same `<textarea>` placed in a `<fieldset>` that is `disabled`:
```html
<form>
    <fieldset>
        <div class="field textarea min label">
<textarea>
One
Two
Three
Four
</textarea>
        <label>Input</label>
         </div>
    </fieldset>

    <fieldset disabled>
        <div class="field textarea min label">
<textarea>
One
Two
Three
Four
</textarea>
        <label>Input disabled</label>
         </div>
    </fieldset>

</form>
```

renders as:
<img width="616" alt="Scherm­afbeelding 2024-08-05 om 08 44 13" src="https://github.com/user-attachments/assets/718533d5-12da-41eb-9ec3-dc8a00976445">

The problem seems to be solved by adding the following css:

```css
  .field>textarea {
      white-space: pre-wrap;
  }
```

**Comment by leonardorafael** [comment]
Fixed in https://github.com/beercss/beercss/releases/tag/v3.6.13
