### ISSUE TITLE
[Feature request] Forcefully toggle element active/inactive

### ISSUE THREAD

**Issue by kwaitsing** [beercss/beercss#349]
```ts
const toggleNewPlan = () => {
        ui('#newPlanBG')
        ui('#newPlanDrawer')
    }

return (
        <>
            <header>
                <button onClick={toggleNewPlan} className="circle transparent">
                    <i>add</i>
                </button>
            </header>
            <div onClick={toggleNewPlan} id="newPlanBG" className="overlay blur"></div>
           
            <dialog id="newPlanDrawer" className="right no-padding">

            </dialog>
)
```

When i clicked on the blur overlay, ui() added the active class to those elements, this is not the excepted behaviour, those elements' active class should be removed

**Comment by leonardorafael** [comment]
Hi @kwaitsing ,

When you use `ui()` or `data-ui` trigger method on elements, it will add the `active` helper on all related elements. You don't need to active the overlay.

https://codepen.io/leo-bnu/pen/xxodwKN

**Comment by kwaitsing** [comment]
Thanks, that's amazing but confusing at first 👍
