### ISSUE TITLE
Article grid margins

### ISSUE THREAD

**Issue by franzvezuli** [beercss/beercss#350]
Hello, I want to display a grid of cards, this is an example setup

```
<div class="grid">
  <article class="m2 center-align">
    <img class="circle large" src="https://i.pravatar.cc/300" alt="user avatar" />
    <p>Test Name</p>
  </article>
  <article class="m2 center-align">
    <img class="circle large" src="https://i.pravatar.cc/300" alt="user avatar" />
    <p>Test Name</p>
  </article>
  <article class="m2 center-align">
    <img class="circle large" src="https://i.pravatar.cc/300" alt="user avatar" />
    <p>Test Name</p>
  </article>
</div>
```

https://codepen.io/franzvz/pen/JjQJKWQ

Why is there a `16px` top-margin being added to the top of every article besides the first one in the grid?

![image](https://github.com/user-attachments/assets/0ae9013e-3ae1-4319-b4f7-9a04f2665707)

I tried `row` instead of `grid` and it looks better. But `row` does not wrap around responsive I don't think, so I figured `grid` was the right choice.

Is there a better way to create cards in a flex view that is also responsive and wraps to the next line(s) ?
I looked at https://github.com/beercss/beercss/issues/325 but it didn't really answer my question

**Comment by leonardorafael** [comment]
Hi @franzvezuli 

Try do this inside grid:

```html
<div class="m2">
  <article>...</article>
</div>
```

**Comment by leonardorafael** [comment]
Fixed in https://github.com/beercss/beercss/releases/tag/v3.6.13

**Comment by franzvezuli** [comment]
Thank you so much @leonardorafael ! Both for the work around and the fix, I'll pull down the new release as well.
