### ISSUE TITLE
Improvement: Set max height for modal so the bottom doesn't go off screen for modals with long content

### ISSUE THREAD

**Issue by denno020** [beercss/beercss#36]
Currently, modals' height restriction is set to 100%, which means if we're using them to display some long form content, e.g. a Privacy Policy or Terms and Conditions, the bottom of the modal will push below the bottom of the users viewport.

Functionally users are also unable to get to the bottom of the modal content when scrolling

My suggestion would be to add the same offset for the bottom of the modal that is used for the top (at least for the "center" variation of the modal).

**Proposition**
Before:
![Modal Before](https://user-images.githubusercontent.com/2059313/152604608-646c61b9-fb90-4914-8539-91b08705282a.gif)

After:
![Modal After](https://user-images.githubusercontent.com/2059313/152604625-270b28b7-414e-44be-b2e7-e967a502f545.gif)

**The Code**

This fix was achieved by editing the `.modal` class:

```
.modal {
  /* ... */
  max-height: calc(100vh - 20%);
  /* ... */
}
```

We can't give `bottom: 10%`, because that will result in the modal always being the full height of the viewport, even when the content of the modal is relatively short. So alternatively, we set the height to be the full viewport, minus the 10% offset for the top, minus the 10% offset we're trying to achieve for the bottom as well.

This change will affect the left/right variations, so we'll need to update those too, resetting `max-height` back to 100%:

```
.modal.right,
.modal.left {
  max-height: 100%;
}
```

If this is an improvement we would like to make, I'd be happy to put together a pull request

**Comment by leonardorafael** [comment]
Nice @denno020 

Thanks for that. "A PR you must to do" 🍻 Can you open a PR with a codepen to test this?

**Comment by myrp-everton** [comment]
Great sugestion @denno020 

Thanks for the feedback.
