### ISSUE TITLE
Everything is italic

### ISSUE THREAD

**Issue by Rewerson** [beercss/beercss#365]
Got very strange behaviour on latest update. See screnshot below.
Browsers are: Edge, Chrome, Firefox, Vivaldi. All are updated to latest stable versions. All are in private mode, so without any cached files, also i directly set ignore cache in dev tools. All are on your page, even not on my own site, so it's not some bug in my code, but I can't explain where is the problem.
Only Edge and Firefox shows normal text on site, but all others makes text on site italic.
On my own project there is the same situation, when updating to 3.6.13 - italic default font, when reverting to 3.6.12 - everything is ok.
![vivaldi_Qdf6aeJTVa](https://github.com/user-attachments/assets/f65345aa-a27e-4558-9b3e-cf5446873ca8)

**Comment by leonardorafael** [comment]
Interesting, you have the same browser versions of mine, except SO. 🤯

**Comment by Rewerson** [comment]
Yes. Really only thing that i suppose, different browsers get CSS from different CDN nodes.

**Comment by Rewerson** [comment]
Seems somehow it's fixed in 3.7.0.
I'll close this issue.
