### ISSUE TITLE
Active labels do not render properly for form elements.

### ISSUE THREAD

**Issue by ciukstar** [beercss/beercss#374]
`.active` labels do not render properly with form elements that are empty and not focused (see image below).

It's also quite noticeable that there are two lines overlapping each other. It's a little bit, but it's quite noticeable.

```beercss@3.7.8```

![Screenshot from 2024-09-13 20-11-42](https://github.com/user-attachments/assets/3b65aa4f-1425-46a5-9bc3-ba6f03548160)

**Comment by leonardorafael** [comment]
Hi @ciukstar ,

When you use the `active` helper on `label`, you need to add the `active` helper on `input` too.
You don't need to add `active` helper when you are loading the JS file.
If you not use the JS file you can add a `placeholder=" "` on input to do the job (a pure CSS solution).

More about trigger helpers here:
https://github.com/beercss/beercss/blob/main/docs/INPUT.md#triggers

**Comment by leonardorafael** [comment]
Are you loading another css that could be affected the borders of fields?
Could you provide a codepen with this issue?

**Comment by leonardorafael** [comment]
I noticed that in your example your label is positioned a bit upper.

**Comment by ciukstar** [comment]
> Hi @ciukstar ,
> 
> When you use the `active` helper on `label`, you need to add the `active` helper on `input` too. You don't need to add `active` helper when you are loading the JS file. If you not use the JS file you can add a `placeholder=" "` on input to do the job (a pure CSS solution).
> 
> More about trigger helpers here: https://github.com/beercss/beercss/blob/main/docs/INPUT.md#triggers

Thanks. Everything works fine if I add `active` to the class list of the input.

**Comment by ciukstar** [comment]
> Are you loading another css that could be affected the borders of fields? Could you provide an codepen with this issue?

No longer an issue. 
This issue only seems to occur in Chrome Developer when the device toolbar is enabled, at 75% zoom or less (on Ubuntu).

...at least now I realize that I work in this Chrome Developer mode most of the time.

Thank you for considering this "issue".

**Comment by ciukstar** [comment]
Issue resolved
