### ISSUE TITLE
Import cycles; unhandled returned promises; misc

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#375]
Using this bug to document misc nit-picky things I found in the typescript code that I thought I could clean up:

At the moment, [`cdn/elements/dialog.ts`](https://github.com/beercss/beercss/blob/main/src/cdn/elements/dialogs.ts) imports from [`cdn/utils.ts`](https://github.com/beercss/beercss/blob/main/src/cdn/utils.ts) which imports cyclicly from [`cdn/elements/dialogs.ts`](https://github.com/beercss/beercss/blob/main/src/cdn/utils.ts#L1).

The same cyclic import situation exists between `cdn/utils/ts` and:

- [cdn/elements/menus.ts](https://github.com/beercss/beercss/blob/main/src/cdn/elements/menus.ts)
- [cdn/elements/pages.ts](https://github.com/beercss/beercss/blob/main/src/cdn/elements/pages.ts)
- [cdn/elements/snackbars.ts](https://github.com/beercss/beercss/blob/main/src/cdn/elements/snackbars.ts)

Even though vite / typescript / etc handle cyclic imports, its generally not recommended for various reasons (from our friend chatgpt):

> 
> Cyclic imports in TypeScript (or any programming language) are generally not recommended due to several potential issues that can arise, affecting both the functionality and maintainability of your codebase. Here’s why:
> 
> 1. Unpredictable Behavior
> 
> 	•	Initialization Order Issues: When two or more modules depend on each other, the order in which these modules are initialized can become unpredictable. This can lead to situations where one module tries to access another module that hasn’t been fully initialized yet, leading to undefined values or runtime errors.
> 	•	Incomplete Module Imports: In a cyclic dependency, when Module A imports Module B, and Module B imports Module A, one of these modules may not be fully loaded when the other tries to use it. This can cause incomplete or incorrect behavior in your application.
> 
> 2. Maintenance Complexity
> 
> 	•	Harder to Understand: Cyclic dependencies create a web of interdependencies that can be difficult to understand and debug. It can be challenging to track down where issues are coming from, especially in a large codebase.
> 	•	Tight Coupling: Cyclic dependencies often indicate that your modules are too tightly coupled. This makes the code harder to maintain and refactor, as changes in one module can ripple through the cycle, leading to unexpected side effects.
> 
> 3. Code Smell
> 
> 	•	Design Flaw Indicator: Cyclic dependencies often point to a flaw in the design of your application. Typically, it suggests that your modules are not sufficiently decoupled, and your application architecture might benefit from a refactor to better separate concerns.
> 
> 4. Tooling and Compilation Issues
> 
> 	•	Compilation Errors: TypeScript and other transpilers or bundlers can sometimes struggle with cyclic dependencies, leading to compilation errors or warnings. While TypeScript’s module system can handle many cases, it’s not always reliable, especially as the complexity of the cycles increases.
> 	•	Circular Dependency Warnings: Many tools, like Webpack or Rollup, will warn about circular dependencies, indicating that the code may not behave as expected.
> 
> 5. Increased Cognitive Load
> 
> 	•	Difficult Debugging: Debugging cyclic dependencies is more complex because of the intertwined nature of the modules. Developers need to consider multiple modules simultaneously, which increases cognitive load.
> 	•	Unexpected Changes: Refactoring or making changes in one module can have unexpected side effects on others due to the cyclic nature of the imports, making even minor changes risky.
> 
> How to Avoid Cyclic Imports
> 
> 	1.	Refactor Code: Break down large modules into smaller, more focused modules with well-defined responsibilities. This can help to reduce or eliminate the need for cyclic dependencies.
> 	2.	Use Dependency Injection: Instead of importing a module directly, consider passing dependencies as parameters to functions or constructors. This can help decouple the modules.
> 	3.	Use Interfaces or Abstract Classes: Sometimes, introducing an interface or abstract class can help break the cycle by reducing direct dependencies between concrete implementations.
> 	4.	Reorganize Module Structure: Sometimes simply reorganizing where modules are located can help avoid cyclic dependencies. Group related modules together in a way that reduces interdependence.
> 
> In summary, cyclic imports in TypeScript are not recommended because they can lead to unpredictable behavior, make the code harder to understand and maintain, indicate design flaws, and cause issues with tooling and compilation. It’s generally better to refactor your code to avoid these kinds of dependencies.
> 

All we need to do is move the `run()` function out of `cdn/utils.ts` and put it into `cdn/beer.ts` file, and the cyclic imports problem gets resolved.

In `cdn/beer.ts` in the function `onClickElement()` we see the call to the `run()` function. The function returns a `Promise` object that is not handled by the caller such as by adding a chained `.then()` call to the return value of `run()`. It can become difficult to understand to the person reading this code about whether `.then()` is missing because the original author of that function forgot it, or whether he/she intentionally omitted it. One way to make this clear to the reader is by simply adding a `void` in front of the `run(...)` method call indicating that not handling the returned `Promise` is an intentional decision. This issue is found in a few different places in the code.

**Comment by leonardorafael** [comment]
Merged, thanks!
