### ISSUE TITLE
Labeled input broken in sveltekit

### ISSUE THREAD

**Issue by Mehybinator** [beercss/beercss#379]
This problem happend when i was trying beercss in a sveltekit spa application, after clicking on the input and entering some text in the input, you would expect the label to stay up, but in svelte the label just comes down, overlapping itself with the ttext inside the input, the html snippet on the github page works as expected, the main website is also working as expected.
### Steps to reproduce :
```
pnpm create svelte@latest tempfront
```
```
cd tempfront
```
```
pnpm install
```
```
pnpm add beercss
```
After the installations have finnished, just go to the src/routes folder in the project folder and edit `+page.svelte` file to look like this :
``` Svelte
<script lang="ts">
  import "beercss/dist/cdn/beer.min.css";
</script>

<div class="field label border">
  <input type="text" />
  <label>Label</label>
</div>
```
Due to sveltekits SSR modules, importing beercss as a window object is not possible in this mode, however since my own project is SPA, i have this in my code :
``` Svelte
<script lang="ts">
	import 'beercss';
</script>

<div class="field label border">
	<input type="text" />
	<label>Label</label>
</div>
```
Run the server :
```
pnpm run dev -- --open
```
Neither of the provided methods have worked.
![2024-10-02_12-38](https://github.com/user-attachments/assets/c6b9fb2f-e6a0-4570-9c6e-c3c78a0bd48b)

**Comment by leonardorafael** [comment]
Hi @Mehybinator , there are other people using Svelte + Beer CSS. Check https://github.com/Materialious/Materialious and try get some help here https://github.com/Materialious/Materialious. I don't have much knowledge in Svelte to help, because Beer CSS is just CSS and a JS file nothing special here.

**Comment by Mehybinator** [comment]
Hello @leonardorafael , thank you for the fast reply, i will look into the project, many thanks.
