### ISSUE TITLE
<footer> covering <dialog> when <progress> present in the DOM

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#388]
This block of css: [https://github.com/beercss/beercss/blob/main/src/cdn/elements/progress.css#L118](https://github.com/beercss/beercss/blob/main/src/cdn/elements/progress.css#L118),

```css
:has(> progress) > :not(progress) {
  z-index: 1;
}
```

is causing an issue where if we have a `<progress>` element in the DOM, then the `<footer>` element seems to cover parts of the `<dialog>` element.

Here is a demo: [https://codepen.io/coffeeandwork/pen/eYqrajY](https://codepen.io/coffeeandwork/pen/eYqrajY).

If I move the `<dialog>` to the very bottom of the `<body>` tag, then the problem goes away, as seen here: [https://codepen.io/coffeeandwork/pen/YzmLbOx](https://codepen.io/coffeeandwork/pen/YzmLbOx). 

This works for now, but it feels like a work-around / hack. The solution seems to be to simply remove the block of css code shown above and the `<footer>` hiding part of the `<dialog>` problem goes away. I was not able to figure out the purpose of this css code block. At a quick glance, removing the code seems to fix the problem and does not seem to cause any other problems. Would it make sense to remove the above block of code? Please advise.

**Comment by leonardorafael** [comment]
Hi @coffeeandwork ,

This code is related to this codepen https://codepen.io/leo-bnu/pen/poLeoQa that use `<progress class="max"></progress>` and all elements must be in front of `progress`. Anyway the css selector is incorrect and need to be fixed. And this could be a solution:

Instead this:
```
:has(> progress) > :not(progress) {
  z-index: 1;
}
```

We need to do this:
```
:has(> progress.max) > :not(progress) {
  z-index: 1;
}
```

**Comment by leonardorafael** [comment]
Fixed on https://github.com/beercss/beercss/releases/tag/v3.7.11
