### ISSUE TITLE
A Menu inside a list doesn't render as expected.

### ISSUE THREAD

**Issue by steevepay** [beercss/beercss#391]
When a button with a menu is placed inside a list item (class row), the `<a>` tags used for menu items inherit from a list item that is also a `<a>` tag.

Example to reproduce the issue:
```html
    <a class="row">
                <div class="max">
                  <h6 class="small" style="margin-top: 5px;">Financial Report 2025</h6>
                  <div>v1.0.0</div>
                </div>
      <button class="circle transparent small">
         <i>more_vert</i>
         <menu class="right no-wrap">
             <a>Deploy in production</a>
             <a>Copy Version ID</a>
             <a>Delete</a>
          </menu>
     </button>
  </a>
```

Screenshot of the result:
<img width="456" alt="Screenshot 2024-12-03 at 20 17 39" src="https://github.com/user-attachments/assets/02f4de9a-9174-4ce1-a1b0-14faec12670e">

I expect the button is located at the end of the row (right side and aligned center inside the row), and the menu without additional spacing, such as:
 
<img width="566" alt="Screenshot 2024-12-03 at 20 27 35" src="https://github.com/user-attachments/assets/80293e2b-c59b-48ed-8cd1-e88edd2f5509">

(screenshot taken from https://material-web.dev/components/menu/)

**Comment by leonardorafael** [comment]
Hi @steevepay ,

Sadly, this is the browser behavior. We can't use nested `<a>` tags.
You will need to use another tag on `<a class="row">`.
You can use `<a class="row">` or just a `<nav>`.

![image](https://github.com/user-attachments/assets/86f87b09-c1b1-4236-acf8-be1ef6bcd84e)

**Comment by steevepay** [comment]
It works, thanks! have a good day Leonardo!

**Comment by steevepay** [comment]
I did not notice, but there is a space difference when I use a `<a class="row">` tag for lists, here is the result (I removed the menu in the button for testing purpose):
<img width="429" alt="Screenshot 2024-12-04 at 12 04 56" src="https://github.com/user-attachments/assets/28d06700-7eb1-4eed-8c86-572ee4fcd6c9">
Here is the result when a `<div class="row"` or `<span class="row"` is used:
<img width="434" alt="Screenshot 2024-12-04 at 12 07 07" src="https://github.com/user-attachments/assets/08028b1e-0e79-489a-b2df-db43f3645b46">
The property "min-block-size: 3rem;" is not applied on div/span.

**Comment by leonardorafael** [comment]
Just the `a.row` has that styles (because it has the purpose to be a clickable item). 
I think we can use the `p.row` like the `a.row` for this use case. 
Seems semantic to me, but needs to implement it:

```html
<div>
  <a class="row">Clickable item</a>
  <p class="row">Clickable item to use links inside it</p>
</div>
```

```css
a.row, p.row {
  min-block-size: 3rem;
  margin: 0;
  cursor: pointer;
}
```

**Comment by leonardorafael** [comment]
Available in https://github.com/beercss/beercss/releases/tag/v3.7.13

**Comment by leonardorafael** [comment]
Please use the newest version here https://github.com/beercss/beercss/releases/tag/v3.7.14
I noticed that `p.row` tag doesn't works well.
You need to use the `nav.row` instead https://github.com/beercss/beercss/blob/main/docs/LIST.md#buttons-and-links-example
