### ISSUE TITLE
Keep active class for tabs/page

### ISSUE THREAD

**Issue by SuperDOS** [beercss/beercss#393]
I noticed that from version 3.7.12 if you have added active class to a tab element in the HTML code it is reset/removed when you click on a nav element. like see codepen: [https://codepen.io/SuperDOS/pen/wBwMaZZ](url)

in the example `<a id="p1tab1" data-ui="#p1ptab1" class="active">Test Page 1 Options</a>` and `div class="page active" id="p1ptab1">` is active and before when you clicked on the nav element to show that page the active tab was shown (also kept active when going to another page) but now you have to click on the tab to show the content.

Is there some way to get it to work as earlier or am I missing something? :)

**Comment by leonardorafael** [comment]
It's a bug, thanks for the catch.

**Comment by leonardorafael** [comment]
Available in https://github.com/beercss/beercss/releases/tag/v3.7.13
