### ISSUE TITLE
The first <nav class="scroll"> elements disappear on very small screens/viewport with Firefox.

### ISSUE THREAD

**Issue by waltrapa** [beercss/beercss#394]
By using following example code in Firefox 133:

Code html:
[nav.txt](https://github.com/user-attachments/files/18027619/nav.txt)

In small viewports the first elements disappear:
![Captura desde 2024-12-05 18-19-19](https://github.com/user-attachments/assets/db881f41-975a-41aa-b444-1492f6d28dcc)

In a wider viewport:
![Captura desde 2024-12-05 18-19-02](https://github.com/user-attachments/assets/6688bab8-77cc-4f53-8a91-052f232728ef)

Web browser: Firefox 133.0
Platform: Ubuntu Linux 24.04 amd64 & Android 12

**Comment by leonardorafael** [comment]
Hi @waltrapa ,

Put a lot of items in the app bars, doesn't seems a good practice. But, if you need do do that, you can add `left-align` to `nav`, to force the left alignment (by default is center aligned):

See here https://codepen.io/leo-bnu/pen/KwPdmEd

**Comment by waltrapa** [comment]
Thanks @leonardorafael,

`left-align` fix this.
