### ISSUE TITLE
Suggestion: Span vertical align middle/unset in toast class

### ISSUE THREAD

**Issue by AlTrAugsburg** [beercss/beercss#40]
Hi, great framework you have here, really like it. It has many interesting concepts and elements, other frameworks don't have. Thank you a lot for your work :heart:

I have but one suggestion: the span-element in the toast class, inside the documentation, is vertically aligned to the bottom, so it looks kinda weird. I would suggest to give a span inside a element with the toast class a vertical alignment of unset or middle like this:

```
.toast span{
     vertical-align: middle;
 }
//Alternative
.toast span{
     vertical-align: unset;
}
```

**Comment by leonardorafael** [comment]
Hi @AlTrAugsburg, thanks for the catch ❤️

I think we can use flex in toasts to fix it. I will do that and release a new version soon.
