### ISSUE TITLE
Add dynamic colors as default or not?

### ISSUE THREAD

**Issue by leonardorafael** [beercss/beercss#41]
Hi guys,

We develop a new package called **material-dynamic-colors** (https://www.npmjs.com/package/material-dynamic-colors). It's a reverse engineer based on the https://material-foundation.github.io/material-theme-builder. This package can be useful if the app needs to change theme at runtime. It has a size of ~10kb minified and gzipped. So my question is:

How about to include it in beer.js file as default?

1) Yes 👍
2) No 👎

React with 👍 or 👎 please

**Comment by leonardorafael** [comment]
Nice point @laurentpayot,

Today it's not too bad for me, using separate files. Maybe just an improvement on documentation resolves. Some thoughts?

## NPM
**Installing**
```
npm i material-dynamic-colors
npm i beercss
```

**Importing**
```
import "material-dynamic-colors";
import "beercss";
```

## CDN
```
<link href="https://cdn.jsdelivr.net/npm/beercss@2.0.12/dist/cdn/beer.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/beercss@2.0.12/dist/cdn/beer.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@0.0.9/dist/cdn/material-dynamic-colors.min.js" type="text/javascript"></script>
```

## Using
```
let theme = await ui("theme", { from: "#ffd700", mode: "dark" });
```

**Comment by laurentpayot** [comment]
In my particular case I’m using my JS framework ([Elm](https://elm-lang.org/)) instead of beercss.js to add `active` classes when activation of elements cannot be done purely in CSS. So I have no access to the `ui()` function. 
Would something like the following be possible to totally decouple themes JS from UI JS?
```js
let theme = await createTheme({ from: "#ffd700", mode: "dark" });
```

**Comment by myrp-leonardo** [comment]
Humm right,

Can we pass the login to `materialDynamicColors()` instead of `ui()`?

**Instead this**
```
ui("theme", { from: "#ffd700", mode: "dark" });
```

**Do this**
```
materialDynamicColors({ from: "#ffd700", mode: "dark" });
```

**Comment by laurentpayot** [comment]
I’ve just read the [material-dynamic-colors readme](https://github.com/leonardorafael/material-dynamic-colors/blob/main/README.md). With a separate file for this, that’s exactly what I needed :smiley: 
```js
let colors = await materialDynamicColors("#ffd700");
```
Thanks @leonardorafael!

**Comment by leonardorafael** [comment]
I will close this issue, we can use separate packages for now.
