### ISSUE TITLE
Suggestion: Update Toast style to use a columned layout

### ISSUE THREAD

**Issue by denno020** [beercss/beercss#42]
Currently toasts seem to just display the elements inline, which means that a longer message, when wrapped, will display underneath the icon.

While it's very much a contextual question, I think a nice default would be to display the content in columns, so that text doesn't wrap underneath the icon, while also updating the vertical alignment.

Currently a longer toast looks like this:

![image](https://user-images.githubusercontent.com/2059313/154060122-6a6bbf57-1805-4473-ad74-522b1f22f791.png)

We could update the styling on `.toast` to have the following:

```
.toast {
  display: grid;
  grid-template-columns: auto 1fr;
  // ...
}
```

which would result in:

![image](https://user-images.githubusercontent.com/2059313/154060368-69a333c0-1571-4041-b2d5-5b28e31b03ac.png)

We could also try and achieve it using flexbox, if we want greater browser support:

```
.toast {
  display: flex;
}
.toast > i {
  flex: 0 0 auto;
}
.toast > span {
  flex: 1 1 auto;
}
```

![image](https://user-images.githubusercontent.com/2059313/154060614-6ac20424-3778-4941-a502-d457dd0e0eed.png)

Finally, using either of the above methods, we could work on the vertical alignment, either by defaulting to top aligned, or centre aligned.

The following is an example using `align-content: center`:

![image](https://user-images.githubusercontent.com/2059313/154060739-88e2c231-4fc7-49fe-b198-a9c931c9ccce.png)

And this is the same example but with more content:

![image](https://user-images.githubusercontent.com/2059313/154061069-87f4ed5c-ad30-4e23-b143-7178328acd59.png)

Or we leave the icon to be top aligned:

![image](https://user-images.githubusercontent.com/2059313/154061426-7e2f5ce3-2647-4000-a0b9-0800e6c270e9.png)

Without any change to the display, the following is how the Toast element will look with the same long message

![image](https://user-images.githubusercontent.com/2059313/154061219-584808b8-d2d1-4035-9b0c-a3cb95574be2.png)

**Comment by myrp-everton** [comment]
Hello @denno020, we strongly recommend to not use huge text in a Toast. 

https://material.io/archive/guidelines/components/snackbars-toasts.html#

**Comment by leonardorafael** [comment]
Done in v2.0.12 https://github.com/beercss/beercss/releases/tag/v2.0.12

We need caution with huge text in toasts guys!
