### ISSUE TITLE
Date input styling?

### ISSUE THREAD

**Issue by m4heshd** [beercss/beercss#44]
Any chance we would get styling for `date` inputs?

![image](https://user-images.githubusercontent.com/6711514/155489396-4f980bbb-d2bb-4e34-ad52-d1ce13401352.png)

Currently I'm overriding the functionality for it to look and work properly.

![image](https://user-images.githubusercontent.com/6711514/155490924-2e90c7a3-216c-4add-8404-8a71c8a64df6.png)

Would be awesome if this was included. 😊 _(I would do a PR but time isn't my friend at the moment)_

**Comment by leonardorafael** [comment]
Hey @m4heshd we will work on it, thanks for suggestions

**Comment by m4heshd** [comment]
@leonardorafael Beautifyl. Thank you for the fast implementation.

**Comment by leonardorafael** [comment]
Hey @m4heshd use https://github.com/beercss/beercss/releases/tag/v2.0.15, because I breaked the labels of selects and textareas in v2.0.14, sorry!

All best!

**Comment by m4heshd** [comment]
@leonardorafael You released the fixed version right when I was about to update the dep. 😁 Thank you for the quick fix. 

Just checked and everything's working perfectly. CSS also appear to be exactly similar to what I had so perfect x 2. 😂
