### ISSUE TITLE
Section with class combinations on home page disappeared

### ISSUE THREAD

**Issue by PotatoesFall** [beercss/beercss#46]
I just noticed the section with all the possible class combination disappeared. Did this information move elsewhere?

Thanks and loving beercss so far, keep up the good work guys :)

**Comment by leonardorafael** [comment]
Hi @PotatoesFall ,

I have been received a lot of messages to improve de docs.
Now we are moving the docs to Github https://github.com/beercss/beercss/blob/main/docs/INDEX.md.
For me, that footer section was very helpful, for others not.
How about I rollback that footer?

**Comment by PotatoesFall** [comment]
Hey @leonardorafael ,

I thought the section was great, would love it if it comes back but I only just got started with beercss so don't take me as authority.

Is there a way to get the same information from the github docs?

**Comment by leonardorafael** [comment]
I always liked the idea of the map with all helpers and elements. I think It's very helpful and easy to learn. I will do that soon.

All best!
