### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by bentwonk** [beercss/beercss#47]
1: how do create a table more than 12 columns wide? Currently only the first 12 columns are shown, with no scroll for further columns :-(
2: is it possible to enable / disable / activate a tab

**Comment by leonardorafael** [comment]
Hi @bentwonk, 

1. Our grid system has 12 columns by default. Can you do a codepen do explain what you want to do? http://www.codepen.io

2. Humm, by the material design specs, tabs do not have a disable state https://material.io/components/tabs#states and https://material.io/design/interaction/states.html#disabled

But for me, it's nice to have a disabled state on tabs. I think we can work on it 🙂

**Comment by bentwonk** [comment]
Thanks fro the quick response: Table: I have a table for results being generated dynamically, the number of columns is determined by the input data and can exceed 12. In data dashboard applications a 12 column table is pretty limiting.  simplified example https://codepen.io/bentwonk/pen/PoEZRzv

I agree disabled tabs is a good way to show future workflow.

**Comment by myrp-leonardo** [comment]
Sorry I did not understant yet, I'll try help. If you use the `row` element you have 12 columns (is a responsive way to do the things). If you use the `<table>` element you do not have column limit. By default, `row` and `<table>` elements will have the width of parent element.

Horizontal scroll is disabled by default. So, if you want horizontal scroll on `<table>` element you need to set a `scroll` helper on parent element, like this:

```
<div class="scroll">
  <table>...</table>
</div>
```

Go to this codepen and resize the window to show the scroll.
https://codepen.io/leo-bnu/pen/WNdxaPa

Is this that you want to do @bentwonk ?

**Comment by leonardorafael** [comment]
Sorry I did not understant yet, I'll try help. If you use the `row` element you have 12 columns (is a responsive way to do the things). If you use the `<table>` element you do not have column limit. By default, `row` and `<table>` elements will have the width of parent element.

Horizontal scroll is disabled by default. So, if you want horizontal scroll on `<table>` element you need to set a `scroll` helper on parent element, like this:

```
<div class="scroll">
  <table>...</table>
</div>
```

Go to this codepen and resize the window to show the scroll.
https://codepen.io/leo-bnu/pen/WNdxaPa

Is this that you want to do @bentwonk ?

**Comment by leonardorafael** [comment]
I will close this issue by inactivity, ok?
