### ISSUE TITLE
Primary text color

### ISSUE THREAD

**Issue by ajusa** [beercss/beercss#48]
Hello!

Thank you so much for making and maintaining this framework! I was wondering if it would be possible to include a `.primary-text` class to change the text color to the primary color. Looking at https://github.com/beercss/beercss/blob/531ed3474f717eadbd3ed839f1f645f6fcf0ba38/src/cdn/helpers/colors.css#L968 I can see that it is implemented for the background color, but not for the text.

In a similar vein, it may be helpful to have .secondary-text.

**Comment by leonardorafael** [comment]
Hey @ajusa 

Thanks! Seems nice to have a *-text too. We will do that soon.

All best!

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v2.0.20
