### ISSUE TITLE
Animation for when `.active` is removed on modals and overlays

### ISSUE THREAD

**Issue by ajusa** [beercss/beercss#52]
Thanks for making beercss, I'm finding it very useful for small projects!

It'd be nice if things like modals and overlays would do the "opposite" effect when they become inactive. When the `active` class is removed, a modal should fly back the way it came and the overlay should become more transparent.

**Comment by leonardorafael** [comment]
Nice point @ajusa, I was waiting for the first one who will notice that. We will do that soon. Thanks for feedback! 👍

**Comment by leonardorafael** [comment]
Hey we do that in https://github.com/beercss/beercss/releases/tag/v2.0.22
