### ISSUE TITLE
Spacing issue with `row no-wrap scroll`

### ISSUE THREAD

**Issue by ajusa** [beercss/beercss#53]
If there are fewer elements than is required for the scrolling, then they will space out the full width. Here's an example from the bottom of the Youtube template with some of the cols removed.

![image](https://user-images.githubusercontent.com/7073362/160940899-a3f72049-48b9-49b1-9fb6-d92dfc8024e9.png)

Ideally the spacing would be consistent no matter how many cols are in the `scroll`.

**Comment by leonardorafael** [comment]
Nice catch, we will fix it soon 🙂

**Comment by leonardorafael** [comment]
Hey we fixed this in https://github.com/beercss/beercss/releases/tag/v2.0.26
