### ISSUE TITLE
dialog element for modals?

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#54]
The [`dialog` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) has finally been [added to Safari](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#html) :tada: 

I’m just creating this issue to know what you think of using `dialog` for modals…

**Comment by leonardorafael** [comment]
Wow, great news. I was waiting to add a `<dialog>` as modal + overlays. Like we have a `.card` as `<article>`.

**Comment by laurentpayot** [comment]
Beware of the "usage relative" stats at https://caniuse.com/dialog
Hopefully both most macOs and iOs users will do the update soon…

**Comment by KicKerBNU** [comment]
A <dialog> for modals would be very nice...
