### ISSUE TITLE
BeerCSS broken on older browsers

### ISSUE THREAD

**Issue by saloniamatteo** [beercss/beercss#61]
Greetings,
I would like to notify you all that BeerCSS does not render properly and is, in fact, broken, on older browsers, such as Firefox <= 72 (IIRC).
When visiting https://beercss.com, some buttons are inaccurately displayed, the icons in buttons either don't load at all or look huge (when they should appear next to the text inside the buttons).

Going to post some screenshots later describing this issue further.

**Comment by saloniamatteo** [comment]
I took some screenshots from FF 65.0:

**beercss.com**

![beercss1](https://user-images.githubusercontent.com/28765699/169527284-d78d606c-be4b-49ae-9fa1-9dac7a8b38df.png)
![beercss2](https://user-images.githubusercontent.com/28765699/169527290-885b48b3-e5ed-451f-9d8d-bc087ae5a634.png)
![beercss3](https://user-images.githubusercontent.com/28765699/169527296-b703e399-ff7e-4a2d-882b-529fd47c222d.png)
![beercss4](https://user-images.githubusercontent.com/28765699/169527309-85dac315-c35a-4206-b756-73575bd47978.png)
![beercss5](https://user-images.githubusercontent.com/28765699/169527320-c8b54ebd-f508-4f32-bb54-b446c0db2fbb.png)
![beercss6](https://user-images.githubusercontent.com/28765699/169527329-6a94ef11-96d9-42ae-84e2-b29836501cba.png)
![beercss7](https://user-images.githubusercontent.com/28765699/169527336-a56d2a9f-268b-4b1f-840c-f7c3ac9c1edf.png)
![beercss8](https://user-images.githubusercontent.com/28765699/169527350-90c8f77b-cb62-4281-8666-a86fe40d33e4.png)

What is noticeably not working are images in buttons, spacing done with divs (e.g. `<div class="space">`), etc.

Here's my website:

**saloniamatteo.top**

Main page:

![salonia-index](https://user-images.githubusercontent.com/28765699/169527619-75bd2d61-4980-4b38-b152-5a3214ef9bf1.png)

Software page:
![salonia-software](https://user-images.githubusercontent.com/28765699/169527731-8e7dcd96-731a-4f9d-82de-89a0c97fb5a5.png)

**Comment by saloniamatteo** [comment]
As you can see on my website BeerCSS doesn't get properly loaded on FF 65.0 (perhaps `<link rel="preload"` is not supported?), however it works fine on newer browsers:
![salonia-index](https://user-images.githubusercontent.com/28765699/169528037-87508cca-a89b-4abd-872a-62912c47ab08.png)
![salonia-index-it](https://user-images.githubusercontent.com/28765699/169528045-70905602-28a6-40b4-b3bb-34a91f4b6d0c.png)

**Comment by saloniamatteo** [comment]
Also, headers are styled differently, for some weird reason:

`<h6 class="card border center-align bold indigo white-text small-padding small-margin"><a href="#lorem-ipsum">Lorem Ipsum</a></h6>`

(See headers like "1. Ottenimento repository", "2. Selezione Versione", etc.)

Firefox 65:
![kern-ff65](https://user-images.githubusercontent.com/28765699/169536899-87afba1c-1f43-4eb4-a95a-ea2266048939.png)

Firefox 98:
![kern-ff98](https://user-images.githubusercontent.com/28765699/169536908-1b8068be-dc05-4dd7-a0b7-16f18f3990ae.png)

**Comment by saloniamatteo** [comment]
Hello,
sorry if there was any confusion: this is a VM with windows 7, that I use solely for testing my work, including this GitHub issue. On my main machine, I use Firefox (Librewolf) 100 and later on  Gentoo Linux, and I do not have any issues whatsoever.

**Comment by saloniamatteo** [comment]
In any case I agree, users should update to newer browsers, I don't really know what the issue is here specifically, but I think it's safe to assume that these older browsers (Chrome as well, not just Firefox) lack the new CSS features implemented.

**Comment by drewbitt** [comment]
Targeting browserslist >0.5% is a good idea. This is then not supported in Opera Mini and UC browser.

**Comment by saloniamatteo** [comment]
I agree with @laurentpayot -- seeing that we cannot easily implement a fix without making the project exponentially bigger, I'm going to close this issue.
