### ISSUE TITLE
Add loading class for inputs

### ISSUE THREAD

**Issue by ajusa** [beercss/beercss#63]
It'd be nice to have a class that can be thrown on an input to give it a spinner on the right side of the element, to show the user that something is loading.

**Comment by laurentpayot** [comment]
+1 I could do this by using an `i` tag with a `loader` class and a custom style, but having this out of the box in Beercss would be great.
@leonardorafael what would you think of also adding a [loading class for buttons](https://uxmovement.com/buttons/when-you-need-to-show-a-buttons-loading-state/)?

**Comment by leonardorafael** [comment]
@laurentpayot I like the idea to use our loader element inside a field element (to respect the same rule as icons and images inside a field element)
