### ISSUE TITLE
Possible to have flyout input label be implemented in pure CSS

### ISSUE THREAD

**Issue by ajusa** [beercss/beercss#64]
Hello,

The input which has the label fly up when focused currently requires the JS provided with beercss. Do you think it is possible to have this be implemented in just CSS? I've seen quite a few codepens that do this, not sure if it is doable for beercss. Feel free to close if this isn't a priority!

![image](https://user-images.githubusercontent.com/7073362/170758750-d6ca5b5c-70f6-4aca-bc49-663cc9ee9320.png)

**Comment by leonardorafael** [comment]
Hi @ajusa ,

Yes you can do a "label up" whitout js here https://codepen.io/leo-bnu/pen/zYzLNGx

But this is not recomended for border inputs, when you have more complex backgrounds like gradients or images. If you have a solid background it's ok.

**Comment by ajusa** [comment]
I see, thanks for the example and the explanation!

**Comment by ajusa** [comment]
I don't think this works anymore - I tried using the codepen link and updating to the latest BeerCSS, and the animation no longer works properly.

**Comment by leonardorafael** [comment]
I updated the codepen to v2.2.6 https://codepen.io/leo-bnu/pen/zYzLNGx
