### ISSUE TITLE
Using as Web Components

### ISSUE THREAD

**Issue by tomatopickle** [beercss/beercss#67]
Is there a way to use Beer CSS components as Web Components? Calling the `ui()` function every time is tedious. Web components make it very easy to make a good UI fast, without any JS. It also makes code more readable. Another advantage is that if it can be used/converted into Web components then using Beer CSS with Vue, React, etc will be a breeze, Currently, every rerender would require another call of the `ui()` function

**Comment by leonardorafael** [comment]
Absolutely. We are working to not call ´ui()´ anymore.

**Comment by leonardorafael** [comment]
Hello @tomatopickle ,

Finally we don't need to call `ui()` anymore in https://github.com/beercss/beercss/releases/tag/v2.1.0 🍺🍺🍺! Just import our js script as usually with zero configuration.

We will think about a web component in future, It's a interesting idea.
