### ISSUE TITLE
[ASK]How to use ui('') in vuejs3

### ISSUE THREAD

**Issue by happyeggchen** [beercss/beercss#71]
i import this at main.js by using
```
import "beercss"
import "material-dynamic-colors"
```

But when i try to use ui('') in vuejs
```
@click.self="ui('products')"
```
it dropped this
```
runtime-core.esm-bundler.js?d2dd:218 Uncaught TypeError: _ctx.ui is not a function
```

**Comment by KicKerBNU** [comment]
Hello @happyeggchen 

We dont need to call the function ui() anymore:
[https://github.com/beercss/beercss/issues/67](url)

I have also done some tests on our Old Codepen with and without ui() everything seems to work fine.
Above some codepens examples that work with ui() and dont need to call the function anymore:
[https://codepen.io/kickerbnu/pen/zYoEqWB](url)
[https://codepen.io/kickerbnu/pen/Yzrgyjj](url)

If you still need help you can give us more information so we can reproduce and fix it or help it xD

Cheers!!


Maybe you can give us more information about the issue?

**Comment by happyeggchen** [comment]
Okay thanks
