### ISSUE TITLE
[Ask]How can i use progress bar as html without trigger ui()

### ISSUE THREAD

**Issue by happyeggchen** [beercss/beercss#72]
[https://github.com/beercss/beercss/issues/67](https://github.com/beercss/beercss/issues/67)

we don't need to call ui() anymore, but i'm wondering how to make items like progress bar move without trigger any script, maybe we can use something like
```html
<template>
<div class="progress left" id="cpu">{{ prec }}</div>
</template>
<script>
export default {
  data() {
    return {
      prec: '40%'
    }
  }
};
</script>
```

**Comment by leonardorafael** [comment]
Hi @happyeggchen 

I think we can't do this without a script. In your example, how about to use a `watch` for `prec`?

```
watch: {
  prec(value) {
    ui("#cpu", value); // a value without %
  }
}
```

**Comment by happyeggchen** [comment]
Sorry ..but i'm new to this
And i don't understand how to import ui() into vue app
That's why i have these question
Currently i'm using
```
import 'beercss'
```
But it doesn't import ui() to vuejs

```
import { ui } from "beercss"
```
didn't help too

**Comment by leonardorafael** [comment]
Ah ok, when you call `import 'beercss'` it creates a `ui()` globally. You can use `ui()` anywhere.

If you are using typescript, you need to declare ui with `declare let ui: any;` in your `env.d.ts` to prevent compiler erros.

**Comment by happyeggchen** [comment]
error  'ui' is not defined
vue cli report this

i use yarn add beercss to install beercss

**Comment by KicKerBNU** [comment]
Are you  importing it correctly?

![image](https://user-images.githubusercontent.com/43939417/179515146-8ca2b3b5-cc8f-4569-ba72-d91ae8c48612.png)

**Comment by happyeggchen** [comment]
![image](https://user-images.githubusercontent.com/38799701/179518864-6476b93e-d573-4dc8-a007-b74fde965645.png)
![Screenshot from 2022-07-18 21-11-52](https://user-images.githubusercontent.com/38799701/179518917-08a306c3-7879-4e8c-a470-afa63e40df54.png)

Yes

**Comment by KicKerBNU** [comment]
Vue CLI uses EsLint so you need to config your global variables on a config file or on each file

Globally:

![image](https://user-images.githubusercontent.com/43939417/179733332-2fa5db7c-c2d8-4669-bda4-546c208bfb00.png)

Or you can declare this variables on each file:

![image](https://user-images.githubusercontent.com/43939417/179733544-d60eb2ae-9eb6-435e-83bf-ec8b6b39bee0.png)

If you need further docs about EsLint:
https://eslint.org/docs/latest/

**Comment by happyeggchen** [comment]
Okay thanks
