### ISSUE TITLE
HELP: dark theme red color

### ISSUE THREAD

**Issue by mxdpeep** [beercss/beercss#73]
I have tried setting theme color to #400000 but in the dark theme it's very light red. I need dark red background for selected navigation items. How?

Thank you for helping me with this, Fred Brooker.

**Comment by leonardorafael** [comment]
Hi @mxdpeep 

You can get more information here https://github.com/beercss/beercss/blob/main/docs/SETTINGS.md#customize-the-default-theme

Beercss has the same structure colors of Material Design 3 https://m3.material.io/styles/color/the-color-system/tokens

**Comment by mxdpeep** [comment]
Thank you for helping me with this.
😍

The documentation for the project needs some extensive work, but I like
it's simplicity (moving from MaterializeCSS). 😂

Filip Oščádal 🍀📱

**Comment by mxdpeep** [comment]
it works, thx - tested OK ❤️
