### ISSUE TITLE
Fixed fab

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#75]
I believe the fab is largely meant to be fixed.

**Comment by leonardorafael** [comment]
Hi @janat08 ,

You can use our absolute/fixed positions to put your FAB in any position. Absolute is relative to container. Fixed is relative to document.

Docs
https://github.com/beercss/beercss/blob/main/docs/LAYOUT.md

Codepen example
https://codepen.io/leo-bnu/pen/LYdrLYQ

All best
