### ISSUE TITLE
Links are not obvius

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#76]
Looks just like text, you have to do things like giving it text of click me.

**Comment by KicKerBNU** [comment]
The documentation of beercss is using a <p class="link"> causing misunderstandings on how to use a link, maybe we can change the documentation usage to <a class="link">.  @janat08  probably is spectating a cursor pointer on his link

**Comment by janat08** [comment]
Are specs saying they should be that? I think google tried not underlining
or not blueing the links, and not for long.

**Comment by leonardorafael** [comment]
I think the material design itself, does not have a common way to do links. But, in beercss, we have a helper called `link`. Actually it only changes the text color to primary color. This is what we have right now.

**Comment by janat08** [comment]
Fair enough, the material loves its new colors now. They have an actual theme CSS export with all the variables derived from 3 colors. https://m3.material.io/theme-builder#/custom

**Comment by janat08** [comment]
It's grey without underline in typography section of docs and also in my
app. As if inside a nav element I suppose.
