### ISSUE TITLE
modal vfx - help needed 

### ISSUE THREAD

**Issue by mxdpeep** [beercss/beercss#78]
in my PWA app https://1950.mxd.cz when you click the top left logo, a modal shows up - but the visual effect is only applied after the second pop up, not on the first one - it just shows the modal without any effects

I am doing something wrong... 😂

any help is greatly appreciated ❤️😎👍

**Comment by leonardorafael** [comment]
Hi @mxdpeep 

Try put `<div class="overlay"></div>` before your modal element. When the modal is activated, we create a overlay if not exists. Or we can fix it delaying the animation of modal to run at 60fps.

**Comment by mxdpeep** [comment]
I have fixed it by removing the hidden class on the load, not before actually showing the modal.

`$('#appinfo_modal').removeClass('hidden');`

and the click function:

`      $('.nav_app').click(function () {
        $('#appinfo_modal').toggleClass('active');
        GSC.modals.push('appinfo_modal');
      });
`
