### ISSUE TITLE
Bugs in Safari

### ISSUE THREAD

**Issue by rorencio** [beercss/beercss#79]
Hi!
I've spotted a couple of bugs when using BeerCSS in Safari, they happen on both iOS and Mac devices:

1. Dropdowns do not open. You click on the button that should open them and nothing happens.
2. Weird new switch animation. For some reason, the animation that plays when a switch is toggled seems to be a bit off. It is hard to describe with words.

Both bugs are reproducible in the https://beercss.com webpage.

That's all for the moment! Congratulations on the library, it's great!

**Comment by leonardorafael** [comment]
Hey @rorencio 

1) With iPhones and Macs, we need to use the default trigger on dropdown https://github.com/beercss/beercss/blob/main/docs/DROPDOWN.md (method 2 is more indicated). The other way, only works on modern browsers. We updated the homepage to use method 2.

2) We are working on it.

**Comment by leonardorafael** [comment]
Fixed in v2.2.10 

https://github.com/beercss/beercss/releases/tag/v2.2.10

**Comment by rorencio** [comment]
Thank you very much!
