### ISSUE TITLE
Great, but button with toast?

### ISSUE THREAD

**Issue by bitdom8** [beercss/beercss#8]
https://www.beercss.com/ checked great framework, but how to do a button with toasts?

**Comment by KicKerBNU** [comment]
Hello bitdom8

I made some codepen examples here: [https://codepen.io/kickerbnu/pen/zYoEqWB](url)

or if you want a single example you can see this one too: [https://codepen.io/kickerbnu/pen/WNoPwjX](url)

**Comment by bitdom8** [comment]
Thanks
