### ISSUE TITLE
beercss.com version selection

### ISSUE THREAD

**Issue by Yoshi20** [beercss/beercss#80]
Hi fellow beer lovers

I started to use beercss (V2.1.x) a few weeks ago and like it a lot.

I discovered today, that V2.2.x was released with quite a few breaking changes.
So ran into the problem that https://www.beercss.com/ no longer shows the content from V2.1.x (for example grid instead of row/col).

Is the V2.1.x page sill available somewhere?
Could you please impl. e.g. a dropdown with a version selection to the get the corresponding documentation?

Keep the good work up.

**Comment by KicKerBNU** [comment]
Hello @Yoshi20 i had the same issue, i used the [https://github.com/beercss/beercss/releases](url) to see the breaking changes and fix codepen problems.

I also dont know if it is feasible to keep site old versions due to financial viability.

**Comment by Yoshi20** [comment]
I've seen the releases and still think it's in general very important to have versioned documentation.

For example:
If I want to come back after a few months (or years) to my website (using beercss). I wouldn't like to first have to update everything just to make us of https://www.beercss.com/ again ;)

**Comment by AlTrAugsburg** [comment]
You could try to view the Documentation in the tree of the old version, e.g. here the INDEX.md of the version 2.1.2:

https://github.com/beercss/beercss/blob/v2.1.2/docs/INDEX.md

I think there should be a documentation of all the elements. The only thing with this solution is, that in works only with version after the version, where the docs were added to the project, which is version 2.0.13

**Comment by KicKerBNU** [comment]
For now we can use the docs to get information about the breaking changes as i said before. @AlTrAugsburg  got the same impression so im gonna close this issue from now.

The breaking changes gonna be extremely rare.
Sorry for any trouble 👌
