### ISSUE TITLE
Clickable lists

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#81]
The button on the right side is technically not necessary since the whole list item is clickable. The buttons are there for secondary action. I suppose that because of that the list items should have a surface or the text be colored as a link (whatever it is that material specifies).

**Comment by janat08** [comment]
This is supppose md latest from web components package with lists not changing much. https://material-components.github.io/material-web/demos/list/

**Comment by leonardorafael** [comment]
Hi @janat08, 
You can use clickable lists using the `row` element.
See more here https://codepen.io/leo-bnu/pen/zYLEQeO. 
I will add this example on Layouts section.

![image](https://user-images.githubusercontent.com/12979016/213150452-91699fa3-d12c-40e4-85c1-932da4a82b6f.png)
