### ISSUE TITLE
upgrading to latest version breaks UI

### ISSUE THREAD

**Issue by mxdpeep** [beercss/beercss#83]
I have tried to upgrade to the latest version (I was about a month late), but the whole UI has broken - is this a common "feature"?

**Comment by leonardorafael** [comment]
Hi @mxdpeep 

After v2.2.0, some elements has been changed. If you want to use the lastest version, we recommend to read all releases after your version. We usually do a before/after examples on changelog notes to help with upgrades.

This can help you to upgrade your project https://github.com/beercss/beercss/releases

Hope you can upgrade it soon my friend

**Comment by mxdpeep** [comment]
thx, I will try later - my app UI works fine so far >> *https://1950.mxd.cz/
<https://1950.mxd.cz/>*

**Comment by bartduisters** [comment]
Just to clean up the issues. @mxdpeep can you confirm (or close) that this issue is solved?
If it was straight forward with the linked release notes, nothing is necessary.
If it was not straight forward - you got it documented / have a commit with the changes? Then docs can be written.

**Comment by mxdpeep** [comment]
it's solved, but not fixed in my app yet (I've just fixed another app with
current Beercss)

**Comment by leonardorafael** [comment]
I will close this, ok?
