### ISSUE TITLE
Overriding rem units and body font size 1px. (incompatible with any other framework).

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#84]
I change font size value on parent div when adding web components for material 3, and none of the fonts show. That would because body have a font size of 1px. Between that and global rem font values this is less than friendly with other frameworks. I'm not quite sure how to override this.

**Comment by janat08** [comment]
Beercss breaks when you change --variable to 16px or something.

**Comment by janat08** [comment]
Is there some other workaround?

**Comment by bartduisters** [comment]
I was not happy with the `--size: 1px;`, so I opened a PR to set it to the normal default for browsers: `--size: 16px;`. This resulted in dividing all existing rem values used in the project by 16.

If you want this in your project as well, you can currently fork the project and cherry-pick this commit:
https://github.com/beercss/beercss/pull/98

**Comment by bartduisters** [comment]
It should.

With migration step:
- If any sizing is `rem` based using beercss v2, it should now be divided by 16. e.g. `padding: 16rem;`will become `padding: 1rem;`, `font-size: 84rem;` will become `font-size: 5.25rem;`.

**Comment by leonardorafael** [comment]
Will be available in 3.0.0 version.

**Comment by JulienMaille** [comment]
It also breaks custom scaling with `:root {--size: 0.95px;}`

**Comment by leonardorafael** [comment]
I updated the release notes https://github.com/beercss/beercss/releases/tag/v3.0.0, thanks for feedback @JulienMaille

**Comment by JulienMaille** [comment]
Thanks for your work!
