### ISSUE TITLE
Dropdown does not work with iOS

### ISSUE THREAD

**Issue by ngmy** [beercss/beercss#85]
Dropdown does not work with iOS.
My iOS version is 15.6.1.

https://codepen.io/ngmy/pen/QWraZzJ

Is there something missing in my code...?

**Comment by KicKerBNU** [comment]
Hello @ngmy, i have tested beercss dropdowns with my iPhone on home page of beercss and works fine there.

**Comment by KicKerBNU** [comment]
@leonardorafael iphone dropdowns are working only with data-ui, not sure if that was the expected behavior.

@ngmy you can use this method above:
![image](https://user-images.githubusercontent.com/43939417/192599462-1e011568-bc3a-4fe1-b749-a559e0502580.png)

**Comment by ngmy** [comment]
@KicKerBNU 
Thank you!
The `data-ui` method worked as expected on my iPhone!

**Comment by leonardorafael** [comment]
> @leonardorafael iphone dropdowns are working only with data-ui, not sure if that was the expected behavior.
> 
> @ngmy you can use this method above: ![image](https://user-images.githubusercontent.com/43939417/192599462-1e011568-bc3a-4fe1-b749-a559e0502580.png)

It's ok, the dropdown without `data-ui` is a shorthand and works only on modern browsers with chromium/gecko engine (Edge, Chrome, Firefox, Opera). This will not work on any browser in Apple systems, because they are limited to Safari engine (webkit) ☹️
