### ISSUE TITLE
GDPR Compliance and Google Fonts

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#86]
Thank you all for the good work you have done on this project. 

In January 2022, German courts made it so that unless web sites ask permission from their users for using Google Fonts before using it, they may be in violation of GDPR. Here is a blog post that talks about it: [https://cookie-script.com/blog/google-fonts-and-gdpr](https://cookie-script.com/blog/google-fonts-and-gdpr).

beercss seems to rely on Google hosted Roboto font and Material Symbols as found here: [https://github.com/beercss/beercss/blob/main/src/cdn/settings/urls.css](https://github.com/beercss/beercss/blob/main/src/cdn/settings/urls.css)

I would like to propose that instead of depending on Google hosted Roboto font and material symbols, we self host them within the project. By self hosting the font files, any project that uses beercss will not have to worry about building UIs for asking for user permission.

**Comment by laurentpayot** [comment]
@coffeeandwork If you do a custom build of beercss, you can simply comment [the line of beer.css importing the url file](https://github.com/beercss/beercss/blob/0f5b675e45a74787be925cc6a035df4f061ad1a2/src/cdn/beer.css#L1).
That’s what I do. Then I manage how I get Roboto and the icons myself.

**Comment by coffeeandwork** [comment]
Thank you @laurentpayot.  I am wondering whether it would make sense to have self hosted fonts and icons as the default behavior. I would be happy to do a PR that will add the font / icon files into the repository and have the code refer to it. Thoughts?

**Comment by myrp-leonardo** [comment]
Hi, I have some questions about GDPR.

1) This law of GDPR about IP addresss, applies only on Europe?
2) Are all Google domains GDPR incompatible?
3) There are any CDN service that are compatible with GDPR? Like jsdelivr, unpkg...?
4) If not, how we can use beercss or any other lib as CDN, without to tell user about it?

Oh boy 😩

**Comment by coffeeandwork** [comment]
@myrp-leonardo I will try to answer your questions below. However, I am not a lawyer, so please do not rely solely on my replies to make decisions around GDPR compliance for your project(s).

1. Here is the homepage of the GDPR laws https://gdpr-info.eu/. GDPR seems to be applicable when providing services to citizens of member nations of the EU. [This page](https://gdpr-info.eu/art-2-gdpr/) seems to provide details on which nations are involved.
2. My impression is that google.com itself is GDPR compliant. If you go to www.google.com at the bottom of the page, you might find a link to their Privacy Policy. [This part of the privacy policy](https://policies.google.com/privacy/frameworks?hl=en&fg=1) seems to have information about Google's compliance with GDPR. I think the issue isn't so much that Google is not complaint, the issue is that if you are loading assets hosted by Google on your web pages, then when your users visit your web page from their devices, Google's servers receive HTTP requests from which Google can collect personal data about your users. Your users might be totally unaware that this is happening in the background. So what the GDPR regulation attempts to do is ensure that unaware users are informed and their permission is required before any personal data can be collected by Google.
3. GDPR and its enforcement seems to be a developing story. It is not clear how/when EU courts will take enforcement action. I prefer to be cautious and self host.
4. Quite a dilemma indeed. For what its worth, and only as far as I know, Google hosted fonts were specifically targeted by German courts in their decision. I don't think they made blanket claims of "other CDN" usage violating compliance.

I wouldn't risk non-compliance. [The fines](https://gdpr-info.eu/issues/fines-penalties/) are severe -- "the fine framework can be up to 20 million euros, or in the case of an undertaking, up to 4 % of their total global turnover of the preceding fiscal year, whichever is higher"

**Comment by mxdpeep** [comment]
as I live in Czechia, I am also voting for the alternate build with locally hosted font files

making it easy, like using the minified CSS/JS, just another folder with font files under the path for the CSS file?

**Comment by coffeeandwork** [comment]
@mxdpeep Thanks for your comments. How would everyone feel about actually getting rid of Google Fonts and Material Symbols entirely from the base build?

The biggest differentiator of beercss seem to be small bundle sizes without compromising on the aesthetics of the UI widgets.

Google Fonts and Material Symbols seem to add 100's of kilobytes to you webpage if you use the current build of beercss.

Google Roboto font can be replaced with system fonts. [Here is a pretty good article](https://css-tricks.com/snippets/css/system-font-stack/) that talks about this concept in general. Adding some css like this might do the trick:

```css
body {
  font-family: system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

Further, instead of loading the whole material symbols library, we can instead use SVG icons. So for example, instead of having:

```html
<i>arrow_upward</i>
```` 

to show an up arrow icon, we can instead have 

```html
<svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M22.5 40V13.7L10.1 26.1 8 24 24 8l16 16-2.1 2.1-12.4-12.4V40Z"/></svg>
```

Of course, more work needs to be done to ensure the SVG icon fits in with the color theme used. We could also alternatively have a directory with a bunch of `.svg` files that get referenced every time a relevant icon is needed. The benefit of doing it this way, is that it helps ensure that only the icons that are needed by the library are loaded.

I would be happy to put together some PRs for this, if there is sufficient interest. The PR for replacing Google roboto font with the system fonts as default will be very quick. Replacing Material Symbols with SVGs will take some time.

Anyone who wants to use Google Roboto or any other font, can still do so, but the base build becomes smaller in this way.

Thoughts?

**Comment by laurentpayot** [comment]
> Adding some css like this might do the trick:
> 
> ```css
> body {
>   font-family: system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
> }
> ```
Beercss is [already doing that](https://github.com/beercss/beercss/blob/24a42aadc045d5bd73b2b94e48be9c2d36318b29/src/cdn/settings/light.css#L35), see #12. So the Roboto font is already optional and should be easy to remove from the build if decided so.

> to show an up arrow icon, we can instead have
>
> ```html
> <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M22.5 40V13.7L10.1 26.1 8 24 24 8l16 16-2.1 2.1-12.4-12.4V40Z"/></svg>
> ```
I agree. [MaterialDesign icons](https://github.com/Templarian/MaterialDesign-SVG) have *a lot* of them. I’m actually using their JS flavor to inject only the needed svg data into my [Elm](https://elm-lang.org/) code but that’s another story...
For a good replacement of the font icons in Beercss I had to set my SVGs width and height to 1em, the wiewbox to `0 0 24 24`, and the path fill color to `currentColor` . I also added the `aria-hidden` attribute for accessibility:

```html
<svg width="1em" height="1em" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M22.5 40V13.7L10.1 26.1 8 24 24 8l16 16-2.1 2.1-12.4-12.4V40Z"></path></svg>
```

**Comment by laurentpayot** [comment]
By the way, what about using [Roboto Flex](https://fonts.google.com/specimen/Roboto+Flex) (a [variable font](https://web.dev/variable-fonts/)) instead of the old Roboto?

**Comment by coffeeandwork** [comment]
> By the way, what about using [Roboto Flex](https://fonts.google.com/specimen/Roboto+Flex) (a [variable font](https://web.dev/variable-fonts/)) instead of the old Roboto?

I have this a try. With old Roboto, browser seems to get about 20 kb of font files over the network. With Roboto Flex seems to climb up to 88 kb.

**Comment by laurentpayot** [comment]
> With old Roboto, browser seems to get about 20 kb of font files over the network. With Roboto Flex seems to climb up to 88 kb

Really? For me Roboto Flex, _without optical size_, but containing all the weights is about 19 KB with the following CSS:
```css
@font-face {
  font-family: 'Roboto Flex';
  font-display: fallback;
  font-style: normal;
  font-weight: 400;
  /* get the newest version URL at https://fonts.googleapis.com/css2?family=Roboto+Flex */
  src: url(https://fonts.gstatic.com/s/robotoflex/v9/NaN4epOXO_NexZs0b5QrzlOHb8wCikXpYqmZsWI-__OGfttPZktqc2VdZ80KvCLZaPcSBZtOx2MifRuWR28sPJtUMbsFEK6cRrleUx9Xgbm3WLHa_F4Ep4Fm0PN19Ik5Dntczx0wZGzhPlL1YNMYKbv9_1IQXOw7AiUJVXpRJ6cXW4O8TNGoXjC79QRyaLshNDUf3e0O-gn5rrZCu20YNYG0EACUTNK-QKavMlx2JoUc5-TkjA.woff2)
       format('woff2-variations');
}
```

**Comment by coffeeandwork** [comment]
Ah I did not try it without optical size. Thanks!

**Comment by coffeeandwork** [comment]
[PR](https://github.com/beercss/beercss/pull/108) ready!

**Comment by coffeeandwork** [comment]
also updated the [self hosting font PR](https://github.com/beercss/beercss/pull/105) with Roboto Flex, hopefully repo owner approves!

**Comment by leonardorafael** [comment]
Hi, we released self hosted fonts on https://github.com/beercss/beercss/releases/tag/v3.0.0
