### ISSUE TITLE
non-active `page` and `modal` take screen space / scroll

### ISSUE THREAD

**Issue by edwindj** [beercss/beercss#87]
First of all, many thanks for this amazing project!

Playing around with tabs and pages I noticed that non active pages (and modal) take screen space: they generate extra scroll/white space at the bottom. That is, in Chrome (Mac, Linux and Android), did not test on different browsers.

I suspect it has to do with `visibility: hidden`, which hides elements, but does not remove them from the document flow: they are still rendered (take space), only not visible. 

Instead of `visibility:hidden`/`visibility:visible` it seems better to use `display:none`/`display:block`  for non active and active elements. 

Cheers,

**Comment by KicKerBNU** [comment]
@edwindj  Thanks for using beercss.

Can you make an [codepen](https://codepen.io/) example to make easier to reproduce the bug?

**Comment by edwindj** [comment]
Sure! :)

https://codepen.io/edwindj/pen/OJZKWNV

- First tab has unneeded scroll, because of size of second tab. 
- If you set img size of second tab to "small" the scroll in the first tab disappears

**Comment by leonardorafael** [comment]
Will be released in next version 👍
