### ISSUE TITLE
Offset on row

### ISSUE THREAD

**Issue by coendr** [beercss/beercss#9]
I didnt see an offset in the row section of the site, is this feature already implemented?
![rows](https://user-images.githubusercontent.com/50136539/112961792-fc80c300-9145-11eb-95df-521934a87aae.png)

**Comment by leonardorafael** [comment]
The offset grid system is not implemented yet. We get the basic grid system for now. We are considering to add this soon, depending of demand.

**Comment by bubnenkoff** [comment]
UP
