### ISSUE TITLE
Request: Hidden on size xx

### ISSUE THREAD

**Issue by Zanoshky** [beercss/beercss#90]
Hello,

Would it be possible to implement a new helper?

Hidden div on small, medium, large or, xl.
Or only visible div on small, medium, large or xl.

Thank you.

**Comment by AlTrAugsburg** [comment]
Hi Zanoshky, 
have you tried the "s", "m" and "l" helper? They help with responsive design. An element, that has the "s" class, is only visible on small displays, e.g. smartphones, "m" on medium displays, e.g. tablets and small laptops, and "l" on large screens, e.g. desktop PCs. They can also be combine, so something is not visible on small screens, but on medium and large screens (give that element the "m" and "l" class).
Hope, I could help you with that 😊
