### ISSUE TITLE
Primary / secondary tabs

### ISSUE THREAD

**Issue by laurentpayot** [beercss/beercss#92]
I loved how v2.3.0 updated tabs from material design 3 guidelines. However, I had to add a few custom CSS rules to get closer to the MD3 specs and get _primary_ and _secondary_ tabs.
My custom CSS is here: https://codepen.io/laurentpayot/pen/RwJGmmv

Do you think `primary-tabs` and `secondary-tabs` classes (or something like that) could be added to beercss to stick to the MD3 guidelines?

**Comment by amery** [comment]
shouldn't this be .tabs.primary and .tabs.secondary instead of .tabs.primary-tabs and .tabs.secondary-tabs to meet the "beercss" rules?

**Comment by laurentpayot** [comment]
@amery the `.primary` and `.secondary` classes are already used to define text color/background: https://github.com/beercss/beercss/blob/main/src/cdn/helpers/theme.css

**Comment by leonardorafael** [comment]
We can use `min`, `max` helpers. It's fine for me. @laurentpayot @amery ?

```
<div class="tabs min|max">
  <a class="vertical active">
    <i>home</i>
    <span>Home</span>
  </a>
  <a class="vertical">
    <i>search</i>
    <span>Search</span>
  </a>
</div>
```

**Comment by laurentpayot** [comment]
@leonardorafael do you mean `min` and `max` relative to the width? Like `min` is for the primary and `max` is for the secondary kind of tab?
If so that’s a good idea, I’m fine with it :+1:

**Comment by leonardorafael** [comment]
Will be available in 3.0.0 version.

**Comment by leonardorafael** [comment]
Released notes https://github.com/beercss/beercss/releases/tag/v3.0.0

**Comment by laurentpayot** [comment]
Awesome v3 release. Thanks @leonardorafael! :+1:
