### ISSUE TITLE
Needs more examples

### ISSUE THREAD

**Issue by ak4nv** [beercss/beercss#95]
As it's noted in the docs

> Build material design interfaces in record time...
> ...without stress for devs

Unfortunately, I wasted a lot of time and could not make a simple dashboard layout like a [this](https://getbootstrap.com/docs/5.2/examples/dashboard/#) or [this](https://coreui.io/docs/getting-started/introduction/) or at least [this](https://picturepan2.github.io/spectre/getting-started.html) one

I'm not front-end guy and I've found that using this framework is too hard for me. All existing templates like a Gmail, Netflix, Uber or Youtube look great but are useless. :-(

Nevertheless, it looks pretty good. Maybe next time I'll use it in another project.

Cheers! :)

**Comment by findborg** [comment]
Bootstrap does not build dashboards like that either.  You have to customize special layouts like that then add the "components"  that you want.  I am sure that if you come back at a later date you will see that someone has put out some layouts like you linked to.  [Here is something that you could start with](https://codepen.io/captproton/pen/JjRpjej).
Good luck.

**Comment by leonardorafael** [comment]
I will close this, ok?
